/* Ilíada — Canto IV
   Tradução em versos livres. */

window.ILIADA.cantos.push({
  numero: 4,
  romano: "IV",
  titulo: "A trégua quebrada",
  estrofes: [
    {
      titulo: "Os deuses bebem e discutem",
      versos: "1–19",
      linhas: [
        "Os deuses, sentados junto a Zeus, no soalho de ouro,",
        "estavam em assembleia; e entre eles a senhora Hebe{1}",
        "servia o néctar; e uns aos outros brindavam com taças de ouro,",
        "olhando para a cidade dos troianos.",
        "Logo o filho de Crono tentou provocar Hera",
        "com palavras ferinas, falando de lado:",
        "“Duas deusas são as protetoras de Menelau:",
        "Hera de Argos e Atena de Alalcômenas{2}.",
        "Mas essas ficam sentadas à parte, contentes de olhar;",
        "ao passo que Afrodite, amiga do riso, está sempre ao lado do outro",
        "e afasta dele as sortes da morte —",
        "e agora mesmo o salvou, quando ele já se julgava perdido.",
        "Mas a vitória é de Menelau, caro a Ares.",
        "Pensemos, pois, em como isto há de ficar:",
        "se havemos de acordar outra vez a guerra funesta",
        "e o estrondo terrível da batalha,",
        "ou de lançar amizade entre os dois lados.",
        "Se isso for bem-vindo e agradável a todos,",
        "a cidade do soberano Príamo poderia continuar habitada,",
        "e Menelau levaria de volta Helena de Argos.”"
      ],
      notas: [
        { termo: "Hebe", texto: "Filha de Zeus e de Hera, encarregada de servir a bebida dos deuses." },
        { termo: "Atena de Alalcômenas", texto: "Alalcômenas, cidade da Beócia onde Atena era cultuada." }
      ]
    },
    {
      titulo: "A ira de Hera",
      versos: "20–49",
      linhas: [
        "Assim falou; e Atena e Hera resmungaram,",
        "sentadas lado a lado, tramando males para os troianos.",
        "Atena ficou calada e nada disse, irritada com Zeus pai,",
        "e uma raiva selvagem a tomava;",
        "mas o peito de Hera não conteve a ira, e ela falou:",
        "“Terribilíssimo Cronida, que palavra disseste!",
        "Como podes querer tornar vão e sem efeito o meu trabalho,",
        "e o suor que suei na canseira? Os meus cavalos cansaram-se",
        "enquanto eu juntava o exército, trazendo desgraças",
        "a Príamo e aos filhos dele.",
        "Faze como quiseres; mas nem todos nós, os outros deuses, aprovamos.”",
        "Muito perturbado, respondeu-lhe Zeus que ajunta as nuvens:",
        "“Estranha! Que mal te fazem Príamo e os filhos de Príamo,",
        "para que te enfureças sem parar em arrasar",
        "a cidadela bem construída de Ílion?",
        "Se tu entrasses pelas portas e pelas longas muralhas",
        "e devorasses cru o próprio Príamo, e os filhos de Príamo,",
        "e os outros troianos, talvez então curasses essa tua ira.",
        "Faze como te aprouver; que esta briga, mais tarde,",
        "não venha a ser entre nós motivo de grande contenda.",
        "Mas outra coisa te digo, e guarda-a no teu ânimo:",
        "quando também eu quiser destruir alguma cidade",
        "onde nasçam homens que te sejam caros,",
        "não travarás a minha ira: deixa-me fazer —",
        "pois esta eu te dei de boa vontade, mas com o coração contra.",
        "De todas as cidades que há sob o sol e o céu estrelado,",
        "onde moram os homens que habitam a terra,",
        "a sagrada Ílion era a mais honrada no meu coração,",
        "e Príamo, e o povo de Príamo da boa lança de freixo.",
        "Pois nunca faltou ao meu altar a parte igual do banquete,",
        "a libação e o cheiro da gordura:",
        "foi essa a porção que nos coube por direito.”"
      ]
    },
    {
      titulo: "As três cidades de Hera",
      versos: "50–67",
      linhas: [
        "Respondeu-lhe então a soberana Hera de olhos de novilha:",
        "“Três cidades me são de longe as mais queridas:",
        "Argos, Esparta e Micenas de largas ruas.",
        "Arrasa-as quando elas se tornarem odiosas ao teu coração;",
        "eu não me porei diante delas, nem te farei oposição.",
        "Ainda que eu tivesse ciúme e não te deixasse destruí-las,",
        "nada conseguiria, pois tu és de longe o mais forte.",
        "Mas também o meu trabalho não pode ficar sem efeito:",
        "também eu sou deusa, e a minha origem é a mesma que a tua;",
        "Crono de curvos conselhos gerou-me a mais honrada,",
        "tanto pelo nascimento como por ser chamada tua mulher —",
        "e tu reinas sobre todos os imortais.",
        "Mas cedamos nisto um ao outro, eu a ti e tu a mim;",
        "e os outros deuses imortais nos seguirão.",
        "Manda depressa Atena ao estrondo terrível",
        "dos troianos e dos aqueus,",
        "e que ela faça com que sejam os troianos os primeiros",
        "a fazer mal aos aqueus gloriosos, contra os juramentos.”"
      ]
    },
    {
      titulo: "Atena desce como uma estrela",
      versos: "68–84",
      linhas: [
        "Assim falou; e o pai dos homens e dos deuses não desobedeceu.",
        "Logo disse a Atena palavras aladas:",
        "“Vai depressa ao exército, entre troianos e aqueus,",
        "e faze com que sejam os troianos os primeiros",
        "a fazer mal aos aqueus gloriosos, contra os juramentos.”",
        "Assim dizendo, incitou Atena, que já estava disposta;",
        "e ela desceu num salto dos cumes do Olimpo.",
        "Como o filho de Crono de curvos conselhos manda uma estrela,",
        "presságio para os navegantes ou para um largo exército de homens,",
        "brilhante, e dela saltam muitas faíscas:",
        "assim Palas Atena se atirou à terra e caiu no meio deles;",
        "e o espanto tomou os que viam —",
        "os troianos domadores de cavalos e os aqueus de belas grevas.",
        "E assim dizia um, olhando para o vizinho:",
        "“Ou vamos ter outra vez a guerra funesta",
        "e o estrondo terrível da batalha,",
        "ou Zeus põe amizade entre os dois lados —",
        "ele, que é o despenseiro da guerra dos homens.”"
      ]
    },
    {
      titulo: "Atena tenta Pândaro",
      versos: "85–103",
      linhas: [
        "Assim dizia um, entre aqueus e troianos.",
        "Mas ela entrou no meio da multidão dos troianos",
        "com a figura de um homem, Laódoco, filho de Antenor,",
        "forte com a lança, à procura do divino Pândaro.",
        "Encontrou parado o filho de Licáon, irrepreensível e forte,",
        "e em volta dele as fileiras cerradas dos que trazem escudo,",
        "os que o tinham seguido desde as correntes do Esepo.",
        "Pondo-se a seu lado, disse-lhe palavras aladas:",
        "“Deixarias tu convencer-te por mim, sábio filho de Licáon?",
        "Terias então a coragem de atirar uma flecha rápida em Menelau,",
        "e ganharias agradecimento e glória entre todos os troianos,",
        "e sobretudo diante do príncipe Alexandre.",
        "Dele, antes de todos, receberias com certeza presentes esplêndidos,",
        "se ele visse Menelau, o guerreiro filho de Atreu,",
        "abatido pela tua seta e posto sobre a pira dolorosa.",
        "Vamos, atira no glorioso Menelau,",
        "e promete a Apolo, o nascido do lobo{1}, glorioso com o arco,",
        "sacrificar uma famosa hecatombe de cordeiros primogênitos,",
        "quando voltares para casa, para a cidade sagrada de Zeleia.”"
      ],
      notas: [
        { termo: "o nascido do lobo", texto: "Epíteto obscuro de Apolo: pode significar “nascido do lobo” ou “nascido na Lícia”." }
      ]
    },
    {
      titulo: "O arco de chifre",
      versos: "104–126",
      linhas: [
        "Assim falou Atena, e convenceu-lhe o ânimo insensato.",
        "Logo ele descobriu o arco polido, feito do chifre",
        "de um bode selvagem que ele próprio, uma vez, atingira no peito,",
        "à espreita num esconderijo, quando o animal descia de uma rocha:",
        "acertou-lhe no peito, e ele caiu para trás, sobre a pedra.",
        "Da cabeça dele saíam chifres de dezesseis palmos;",
        "o artífice do chifre uniu-os e ajustou-os,",
        "alisou tudo com cuidado e pôs-lhe uma ponta de ouro.",
        "Pândaro armou o arco, dobrando-o bem,",
        "e pousou-o encostado ao chão; e os companheiros valentes",
        "puseram os escudos diante dele,",
        "para que os filhos guerreiros dos aqueus não se levantassem",
        "antes de ser atingido Menelau, o guerreiro filho de Atreu.",
        "Tirou a tampa da aljava e escolheu uma flecha,",
        "emplumada, nunca disparada, portadora de dores negras.",
        "Depressa ajustou a seta amarga à corda,",
        "e prometeu a Apolo, o nascido do lobo, glorioso com o arco,",
        "sacrificar uma famosa hecatombe de cordeiros primogênitos,",
        "quando voltasse para casa, para a cidade sagrada de Zeleia.",
        "Puxou, segurando juntos o entalhe e a corda de tendão de boi;",
        "trouxe a corda ao peito e a ponta de ferro ao arco.",
        "E quando dobrou o grande arco em círculo,",
        "o arco rangeu, a corda cantou alto,",
        "e a seta aguda saltou, ansiosa por voar para dentro da multidão."
      ]
    },
    {
      titulo: "A flecha desviada",
      versos: "127–147",
      linhas: [
        "Mas os deuses bem-aventurados não se esqueceram de ti, Menelau —",
        "antes de todos a filha de Zeus, a que arrasta despojos,",
        "que se pôs diante de ti e desviou a seta aguda.",
        "Afastou-a da carne como a mãe enxota uma mosca do filho",
        "quando ele dorme um sono doce;",
        "e ela própria a guiou para onde as fivelas de ouro do cinto",
        "se prendiam, e a couraça se fazia dupla.",
        "A seta amarga caiu sobre o cinto bem ajustado;",
        "atravessou o cinto lavrado,",
        "forçou caminho pela couraça bem trabalhada",
        "e pela proteção que ele usava para resguardar a carne,",
        "barreira contra os dardos, que mais o protegia —",
        "e ainda assim passou também por ela.",
        "A flecha roçou a pele mais externa do homem,",
        "e logo o sangue escuro corria da ferida.",
        "Como quando uma mulher da Meônia ou da Cária",
        "tinge marfim de púrpura, para servir de peça de face aos cavalos:",
        "fica guardado numa câmara, e muitos cavaleiros",
        "desejam levá-lo, mas ele fica como tesouro de um rei,",
        "ao mesmo tempo enfeite do cavalo e glória do condutor —",
        "assim, Menelau, se tingiram de sangue as tuas coxas,",
        "as coxas bem-feitas, e as pernas, e os belos tornozelos por baixo."
      ]
    },
    {
      titulo: "O juramento pisado",
      versos: "148–168",
      linhas: [
        "Estremeceu então Agamêmnon, soberano de homens,",
        "ao ver o sangue escuro correr da ferida;",
        "e estremeceu também o próprio Menelau, caro a Ares.",
        "Mas quando viu que o tendão e as farpas estavam fora da carne,",
        "o ânimo voltou a juntar-se-lhe no peito.",
        "Gemendo fundo, falou entre eles o soberano Agamêmnon,",
        "segurando Menelau pela mão, e os companheiros gemiam com ele:",
        "“Irmão querido, foi para a tua morte que eu jurei os juramentos,",
        "pondo-te sozinho diante dos aqueus a combater os troianos,",
        "já que os troianos te alvejaram e pisaram os juramentos fiéis.",
        "Mas o juramento não é em vão, nem o sangue dos cordeiros,",
        "nem as libações puras, nem os apertos de mão em que confiamos.",
        "Pois ainda que o Olímpio não o cumpra já,",
        "há de cumpri-lo tarde; e eles pagarão caro,",
        "com as próprias cabeças, e com as mulheres e os filhos.",
        "Isto eu bem sei, no espírito e no coração:",
        "virá um dia em que há de perecer a sagrada Ílion,",
        "e Príamo, e o povo de Príamo da boa lança de freixo;",
        "e Zeus, filho de Crono, sentado no alto, que habita o céu,",
        "há de sacudir sobre todos eles a égide escura,",
        "irado com este engano. Isto não ficará por cumprir.”"
      ]
    },
    {
      titulo: "O chamado ao curador",
      versos: "169–197",
      linhas: [
        "“Mas terei uma dor terrível por ti, Menelau,",
        "se morreres e cumprires a medida da tua vida.",
        "E eu voltaria coberto de vergonha para Argos sedenta,",
        "pois logo os aqueus se lembrariam da terra dos pais,",
        "e deixaríamos a Príamo e aos troianos, como troféu,",
        "Helena de Argos; e os teus ossos apodreceriam",
        "enquanto jazesses em Troia, com a obra por acabar.",
        "E assim diria algum troiano arrogante,",
        "saltando sobre o túmulo do glorioso Menelau:",
        "‘Que Agamêmnon cumpra sempre assim a sua ira,",
        "como agora, que trouxe para cá um exército de aqueus à toa",
        "e voltou para a terra amada dos pais com as naves vazias,",
        "deixando para trás o nobre Menelau.’",
        "Assim há de dizer alguém; e então que a terra larga se abra para mim.”",
        "Mas Menelau de louros cabelos animou-o:",
        "“Coragem, e não assustes ainda o exército dos aqueus.",
        "A seta aguda não se cravou em lugar mortal:",
        "deteve-a antes o cinto brilhante, e por baixo",
        "a saia de metal e a proteção que os ferreiros fizeram.”",
        "Respondendo-lhe, disse o soberano Agamêmnon:",
        "“Oxalá seja assim, Menelau querido.",
        "Mas um curador há de tratar a ferida",
        "e pôr-lhe remédios que façam parar as dores negras.”",
        "Assim falou, e dirigiu-se a Taltíbio, o arauto divino:",
        "“Taltíbio, chama aqui, o mais depressa que puderes, Macáon,",
        "filho de Asclépio{1}, o curador irrepreensível,",
        "para ver o guerreiro Menelau, filho de Atreu,",
        "que alguém entendido no arco alvejou —",
        "um troiano ou um lício —, glória para ele, e dor para nós.”"
      ],
      notas: [
        { termo: "Asclépio", texto: "Grande curandeiro, pai de Macáon; mais tarde passou a ser cultuado como o deus da medicina." }
      ]
    },
    {
      titulo: "Macáon trata a ferida",
      versos: "198–219",
      linhas: [
        "Assim falou; e o arauto não desobedeceu ao ouvi-lo.",
        "Foi pelo exército dos aqueus vestidos de bronze,",
        "à procura do herói Macáon. Encontrou-o parado,",
        "e em volta dele as fileiras cerradas dos que trazem escudo,",
        "os que o tinham seguido de Trica, pastagem de cavalos.",
        "Pondo-se a seu lado, disse-lhe palavras aladas:",
        "“Levanta-te, filho de Asclépio! Chama-te o soberano Agamêmnon,",
        "para veres o guerreiro Menelau, chefe dos aqueus,",
        "que alguém entendido no arco alvejou —",
        "um troiano ou um lício —, glória para ele, e dor para nós.”",
        "Assim falou, e mexeu-lhe com o coração no peito.",
        "Foram os dois pela multidão, ao longo do largo exército dos aqueus.",
        "E quando chegaram ao lugar onde estava ferido Menelau de louros cabelos,",
        "e todos os chefes reunidos em roda dele,",
        "o homem divino veio para o meio deles;",
        "e logo puxou a flecha do cinto bem ajustado,",
        "e, ao ser puxada, as farpas agudas partiram-se para trás.",
        "Soltou o cinto brilhante e, por baixo,",
        "a saia de metal e a proteção que os ferreiros fizeram.",
        "Quando viu a ferida onde caíra a seta amarga,",
        "chupou o sangue e espalhou por cima, com perícia,",
        "remédios que acalmam, os que outrora Quíron{1}, por amizade,",
        "tinha dado ao pai dele."
      ],
      notas: [
        { termo: "Quíron", texto: "O centauro que criou e instruiu vários heróis, entre eles Aquiles, e era mestre na arte de curar." }
      ]
    },
    {
      titulo: "Agamêmnon percorre as fileiras",
      versos: "220–249",
      linhas: [
        "Enquanto se ocupavam de Menelau,",
        "vinham avançando as fileiras dos troianos que trazem escudo;",
        "e os aqueus vestiram outra vez as armas e lembraram-se da fúria.",
        "Então não verias o divino Agamêmnon a dormir,",
        "nem encolhido, nem sem vontade de combater,",
        "mas com muita pressa da batalha que dá glória.",
        "Deixou os cavalos e o carro brilhante de bronze,",
        "e o servo Eurimedonte segurava à parte os cavalos que bufavam;",
        "a ele deu ordem severa de os ter por perto,",
        "para quando o cansaço lhe chegasse aos membros",
        "de tanto pôr em ordem os seus homens.",
        "E foi a pé, percorrendo as fileiras.",
        "Aos que via dispostos, entre os dânaos de cavalos velozes,",
        "punha-se a seu lado e animava-os com palavras:",
        "“Argivos, não afrouxeis a vossa coragem!",
        "Zeus pai não há de socorrer os mentirosos:",
        "aqueles que primeiro fizeram o mal contra os juramentos,",
        "os abutres lhes comerão a carne macia,",
        "e nós levaremos nas naves as mulheres e os filhos pequenos deles,",
        "quando tomarmos a cidadela.”",
        "Mas aos que via recuando da guerra odiosa,",
        "a esses repreendia com palavras duras:",
        "“Argivos fanfarrões, gente vergonhosa! Não tendes vergonha?",
        "Por que ficais assim parados, como cervas",
        "que, cansadas de correr por uma larga planície, param,",
        "e já não têm força nenhuma no peito?",
        "Assim estais vós, parados, e não combateis.",
        "Estais à espera de que os troianos cheguem perto,",
        "onde as vossas naves de belas popas estão puxadas para a praia",
        "do mar cinzento, para verdes se o filho de Crono",
        "há de estender a mão sobre vós?”"
      ]
    },
    {
      titulo: "Idomeneu",
      versos: "250–271",
      linhas: [
        "Assim percorria as fileiras, dando ordens.",
        "Chegou aos cretenses, atravessando a multidão:",
        "estavam a armar-se em volta do sábio Idomeneu.",
        "Idomeneu ia à frente, valente como um javali,",
        "e Meríones ia atrás, incitando as últimas linhas.",
        "Ao vê-los, alegrou-se Agamêmnon, soberano de homens,",
        "e logo se dirigiu a Idomeneu com palavras de mel:",
        "“Idomeneu, acima de todos os dânaos de cavalos velozes",
        "eu te honro, tanto na guerra como nos outros trabalhos,",
        "e no banquete, quando os primeiros dos argivos",
        "misturam na cratera o vinho de honra{1}, que brilha.",
        "Pois enquanto os outros aqueus de longos cabelos",
        "bebem por medida, a tua taça está sempre cheia,",
        "como a minha, para beberes quando o coração pedir.",
        "Levanta-te para a guerra, e sê o que dizes ser.”",
        "Respondeu-lhe Idomeneu, chefe dos cretenses:",
        "“Atrida, hei de ser para ti um companheiro de confiança,",
        "como prometi e garanti desde o princípio.",
        "Mas levanta os outros aqueus de longos cabelos,",
        "para combatermos o quanto antes,",
        "já que os troianos desfizeram os juramentos.",
        "Morte e desgraças lhes hão de vir depois,",
        "pois foram eles os primeiros a fazer o mal contra os juramentos.”"
      ],
      notas: [
        { termo: "o vinho de honra", texto: "Nos banquetes, alguns chefes tinham direito a beber à vontade, enquanto aos demais se servia uma medida fixa. Era um sinal público de posição, como o prêmio tirado do saque." }
      ]
    },
    {
      titulo: "Os dois Ájax",
      versos: "272–291",
      linhas: [
        "Assim falou; e o Atrida seguiu adiante, contente no coração.",
        "Chegou aos dois Ájax, atravessando a multidão:",
        "estavam a armar-se, e uma nuvem de soldados a pé os seguia.",
        "Como quando um cabreiro, do alto de um posto de vigia,",
        "vê uma nuvem vindo sobre o mar, empurrada pelo vento oeste:",
        "de longe parece-lhe mais negra do que o piche, ao vir sobre o mar,",
        "e traz consigo um grande turbilhão;",
        "ele estremece ao vê-la e mete o rebanho numa gruta —",
        "assim eram as falanges escuras dos jovens criados por Zeus",
        "que iam com os dois Ájax para a guerra furiosa,",
        "eriçadas de escudos e de lanças.",
        "Ao vê-los, alegrou-se o soberano Agamêmnon,",
        "e disse-lhes palavras aladas:",
        "“Ájax, chefes dos argivos vestidos de bronze:",
        "a vós dois não dou ordens, pois não fica bem —",
        "vós mesmos animais o povo a combater com força.",
        "Quem dera, Zeus pai, Atena e Apolo,",
        "que houvesse no peito de todos um ânimo assim:",
        "depressa baixaria a cabeça a cidade do soberano Príamo,",
        "tomada e arrasada pelas nossas mãos.”"
      ]
    },
    {
      titulo: "Nestor põe os seus em ordem",
      versos: "292–310",
      linhas: [
        "Assim dizendo, deixou-os ali e foi ter com outros.",
        "Encontrou então Nestor, o claro orador dos pílios,",
        "a pôr em ordem os companheiros e a animá-los para o combate,",
        "em volta do grande Pelagonte, de Alástor e de Crômio,",
        "do soberano Hémon e de Bias, pastor de povos.",
        "À frente pôs os condutores, com os cavalos e os carros;",
        "atrás deles, os soldados a pé, muitos e valentes,",
        "para servirem de muralha da guerra;",
        "e os covardes empurrou para o meio{1},",
        "para que mesmo contra a vontade cada um tivesse de combater.",
        "Primeiro deu ordens aos condutores, mandando-os segurar os cavalos",
        "e não se embaraçarem na multidão:",
        "“Que ninguém, confiado na sua perícia e na sua coragem,",
        "queira combater os troianos sozinho, à frente dos outros;",
        "nem recue: ficaríeis mais fracos.",
        "Aquele que do seu carro alcançar o carro de outro,",
        "que golpeie com a lança, pois isso é muito melhor.",
        "Foi assim que os homens de antigamente arrasaram cidades e muralhas,",
        "tendo no peito esta ideia e este ânimo.”"
      ],
      notas: [
        { termo: "os covardes empurrou para o meio", texto: "Posição de onde não se pode fugir nem recuar, cercado pelos próprios companheiros." }
      ]
    },
    {
      titulo: "A velhice de Nestor",
      versos: "311–325",
      linhas: [
        "Assim os animava o ancião, havia muito entendido em guerras.",
        "Ao vê-lo, alegrou-se o soberano Agamêmnon,",
        "e disse-lhe palavras aladas:",
        "“Ancião, quem dera que, assim como o ânimo no teu peito,",
        "também os joelhos te obedecessem e a força se mantivesse firme.",
        "Mas a velhice, que é de todos, vai-te gastando.",
        "Quem dera a tivesse outro homem qualquer,",
        "e tu estivesses entre os moços.”",
        "Respondeu-lhe Nestor, o cavaleiro de Gerena:",
        "“Atrida, também eu bem quisera ser como era",
        "quando matei o divino Ereutálion.",
        "Mas os deuses não dão aos homens todas as coisas ao mesmo tempo:",
        "se então eu era moço, agora a velhice me acompanha.",
        "Ainda assim estarei entre os condutores,",
        "e hei de animá-los com conselho e com palavras,",
        "pois esse é o privilégio dos velhos.",
        "As lanças serão atiradas pelos mais novos,",
        "que nasceram depois de mim e confiam na sua força.”"
      ]
    },
    {
      titulo: "Menesteu e Odisseu repreendidos",
      versos: "326–355",
      linhas: [
        "Assim falou; e o Atrida seguiu adiante, contente no coração.",
        "Encontrou parado Menesteu, condutor de cavalos, filho de Peteu,",
        "e em volta dele os atenienses, mestres do grito de guerra.",
        "Perto estava Odisseu de muitos ardis,",
        "e em volta dele as fileiras dos cefalênios, tropa que não é fraca.",
        "É que a gente deles ainda não tinha ouvido o grito de guerra:",
        "as falanges dos troianos domadores de cavalos e dos aqueus",
        "tinham acabado de se pôr em movimento;",
        "e eles esperavam que outra coluna de aqueus avançasse,",
        "atacasse os troianos e começasse a batalha.",
        "Ao vê-los, repreendeu-os Agamêmnon, soberano de homens,",
        "e disse-lhes palavras aladas:",
        "“Filho de Peteu, rei criado por Zeus,",
        "e tu, entendido em maus ardis, ganancioso:",
        "por que ficais à parte, encolhidos, à espera dos outros?",
        "A vós dois ficaria bem estar entre os primeiros",
        "e enfrentar a batalha que queima.",
        "Pois sois os primeiros a ouvir o meu chamado para o banquete,",
        "sempre que nós, aqueus, preparamos a mesa dos anciãos.",
        "Ali gostais de comer carne assada",
        "e de beber taças de vinho doce como mel, o quanto quiserdes.",
        "Mas agora ficaríeis contentes de olhar,",
        "ainda que dez colunas de aqueus combatessem à vossa frente",
        "com o bronze impiedoso.”"
      ]
    },
    {
      titulo: "A resposta de Odisseu",
      versos: "356–375",
      linhas: [
        "Olhando-o de través, respondeu-lhe Odisseu de muitos conselhos:",
        "“Atrida, que palavra te escapou da cerca dos dentes{1}?",
        "Como podes dizer que nos afastamos da guerra,",
        "quando nós, aqueus, levantamos a batalha aguda",
        "contra os troianos domadores de cavalos?",
        "Hás de ver, se quiseres e se te importar,",
        "o pai querido de Telêmaco misturado com os primeiros",
        "combatentes dos troianos domadores de cavalos.",
        "O que dizes é vento à toa.”",
        "Sorriu o soberano Agamêmnon, ao vê-lo irado,",
        "e retirou o que dissera:",
        "“Filho de Laertes, criado por Zeus, Odisseu de muitos recursos:",
        "não te repreendo além da medida, nem te dou ordens;",
        "pois sei que o coração no teu peito conhece pensamentos amigos,",
        "e que pensas como eu.",
        "Vamos, isto havemos de acertar depois,",
        "se agora se disse alguma palavra má;",
        "e que os deuses façam com que tudo isso dê em nada.”",
        "Assim dizendo, deixou-os ali e foi ter com outros."
      ],
      notas: [
        { termo: "a cerca dos dentes", texto: "Fórmula homérica para os dentes: a barreira que devia ter segurado a palavra antes de sair." }
      ]
    },
    {
      titulo: "A história de Tideu",
      versos: "376–400",
      linhas: [
        "Encontrou o filho de Tideu, o altivo Diomedes,",
        "parado junto aos cavalos e ao carro bem armado;",
        "e ao lado dele estava Estênelo, filho de Capaneu.",
        "Ao vê-lo, repreendeu-o o soberano Agamêmnon,",
        "e disse-lhe palavras aladas:",
        "“Ai, filho do sábio Tideu, domador de cavalos:",
        "por que te encolhes? Por que ficas a olhar os corredores da batalha?",
        "Não era assim que Tideu costumava encolher-se:",
        "combatia o inimigo bem à frente dos companheiros queridos —",
        "assim contam os que o viram no trabalho,",
        "pois eu nunca o encontrei nem o vi; mas dizem que era superior aos outros.",
        "Uma vez ele veio a Micenas, não como inimigo, mas como hóspede,",
        "com o divino Polinices, para juntar um exército:",
        "faziam então guerra às muralhas sagradas de Tebas{1},",
        "e muito pediam que lhes dessem aliados ilustres.",
        "Os micênios estavam dispostos a dar e aprovavam o pedido,",
        "mas Zeus os desviou, mostrando sinais de mau agouro.",
        "Foram-se embora, então; e quando chegaram ao Asopo de fundos juncos,",
        "os aqueus mandaram Tideu numa embaixada.",
        "Ele foi, e encontrou muitos filhos de Cadmo{2} em banquete,",
        "na casa do poderoso Etéocles.",
        "Ali, embora estrangeiro, o cavaleiro Tideu não teve medo,",
        "sozinho no meio de tantos cadmeus:",
        "desafiou-os para provas e venceu todas com facilidade —",
        "tal era a ajuda que Atena lhe dava.",
        "Mas os cadmeus, condutores de cavalos, ficaram irados,",
        "e, quando ele voltava, armaram-lhe uma emboscada cerrada",
        "de cinquenta rapazes.",
        "Tideu deu-lhes um fim vergonhoso: matou-os a todos,",
        "e deixou um só voltar para casa —",
        "mandou Méon de volta, obedecendo aos sinais dos deuses.",
        "Assim era Tideu, o etólio. Mas gerou um filho",
        "pior do que ele no combate, ainda que melhor na assembleia.”"
      ],
      notas: [
        { termo: "às muralhas sagradas de Tebas", texto: "A expedição dos Sete contra Tebas: Polinices, expulso pelo irmão Etéocles, juntou sete chefes para retomar a cidade. O ataque fracassou e quase todos morreram. Tideu, pai de Diomedes, foi um deles." },
        { termo: "filhos de Cadmo", texto: "Os tebanos. Cadmo foi o fundador de Tebas, e por isso o poema chama os tebanos de cadmeus." }
      ]
    },
    {
      titulo: "Diomedes cala o companheiro",
      versos: "401–421",
      linhas: [
        "Assim falou; e o forte Diomedes nada respondeu,",
        "respeitando a repreensão do rei venerando.",
        "Mas o filho do glorioso Capaneu respondeu-lhe:",
        "“Atrida, não mintas, tu que sabes falar a verdade.",
        "Nós nos gabamos de ser homens muito melhores do que os nossos pais:",
        "nós tomamos a sede de Tebas das sete portas,",
        "levando um exército menor contra uma muralha mais forte,",
        "confiados nos sinais dos deuses e na ajuda de Zeus;",
        "e eles morreram por causa das próprias loucuras.",
        "Portanto nunca ponhas os nossos pais na mesma honra que a nossa.”",
        "Olhando-o de través, disse o forte Diomedes:",
        "“Fica sentado e calado, amigo, e obedece à minha palavra.",
        "Não levo a mal que Agamêmnon, pastor de povos,",
        "anime os aqueus de belas grevas a combater.",
        "A glória há de segui-lo, se os aqueus matarem os troianos",
        "e tomarem a sagrada Ílion;",
        "e grande será a dor dele, se os aqueus forem mortos.",
        "Vamos, lembremo-nos também nós da coragem furiosa.”",
        "Assim falou, e saltou do carro para o chão, com as armas;",
        "e o bronze retiniu terrivelmente no peito do senhor, ao mover-se —",
        "o medo teria tomado até um homem de coração firme."
      ]
    },
    {
      titulo: "As duas linhas avançam",
      versos: "422–445",
      linhas: [
        "Como na praia que ressoa a onda do mar é empurrada,",
        "uma após outra, sob o impulso do vento oeste:",
        "ao largo ela primeiro levanta a crista,",
        "depois quebra em terra e ruge alto,",
        "e em volta dos promontórios incha e ergue a cabeça,",
        "e cospe a espuma salgada —",
        "assim, fileira após fileira, os dânaos avançavam",
        "sem parar para a batalha.",
        "Cada chefe dava ordens aos seus;",
        "e os outros iam calados — não dirias que um exército tão grande",
        "seguia atrás, com voz guardada no peito —,",
        "calados, com respeito pelos que os comandavam.",
        "E sobre todos eles reluziam as armas lavradas,",
        "enquanto marchavam em ordem.",
        "Mas os troianos, como ovelhas sem conta no pátio de um homem rico,",
        "paradas para dar o leite branco,",
        "que balem sem parar ao ouvir a voz dos cordeiros —",
        "assim subia o clamor dos troianos pelo largo exército.",
        "Pois não tinham todos a mesma fala nem uma só língua,",
        "mas as línguas se misturavam, e eram homens chamados de muitas terras.",
        "A uns incitava Ares, e aos outros Atena de olhos brilhantes,",
        "e o Terror, e a Debandada, e a Discórdia{1}, que se enfurece sem parar,",
        "irmã e companheira de Ares matador de homens —",
        "ela, que a princípio ergue a crista pequena,",
        "e depois planta a cabeça no céu enquanto caminha na terra.",
        "Foi ela que lançou entre eles a briga de todos,",
        "andando pela multidão e aumentando o gemido dos homens."
      ],
      notas: [
        { termo: "o Terror, a Debandada, a Discórdia", texto: "Forças personificadas que acompanham Ares no campo de batalha: o pânico, a fuga e a briga." }
      ]
    },
    {
      titulo: "O primeiro sangue",
      versos: "446–472",
      linhas: [
        "Quando chegaram ao mesmo lugar e se encontraram,",
        "chocaram escudos e lanças e a fúria dos homens vestidos de bronze;",
        "e os escudos de umbigo{1} bateram uns nos outros,",
        "e levantou-se um grande estrondo.",
        "Ali estavam o gemido e a gabarolice dos que matavam e dos que morriam,",
        "e a terra corria de sangue.",
        "Como as torrentes de inverno, descendo das montanhas",
        "a partir de grandes nascentes, atiram juntas a sua água poderosa",
        "para dentro de uma garganta,",
        "e ao longe, nos montes, um pastor ouve o trovão —",
        "assim, do encontro daqueles homens, vinha o grito e a canseira.",
        "Primeiro Antíloco matou um troiano de elmo,",
        "valente entre os que combatem à frente:",
        "Equépolo, filho de Talísio.",
        "Acertou-lhe primeiro na crista do elmo de crina de cavalo",
        "e cravou-lhe a ponta na testa, e o bronze entrou pelo osso;",
        "a escuridão lhe cobriu os olhos, e ele caiu",
        "como cai uma torre na batalha renhida.",
        "Quando ele caiu, o soberano Elefenor pegou-lhe pelos pés —",
        "o filho de Calcodonte, chefe dos abantes de grande ânimo —",
        "e tentou arrastá-lo para fora do alcance dos dardos,",
        "com pressa de lhe tirar as armas; mas pouco durou o esforço.",
        "Pois Agenor, de grande ânimo, viu-o a arrastar o morto,",
        "e, no flanco que o escudo deixara descoberto enquanto ele se abaixava,",
        "golpeou-o com a lança de ponta de bronze e soltou-lhe os membros.",
        "Assim o deixou o ânimo; e sobre ele levantou-se",
        "uma luta dura de troianos e aqueus:",
        "como lobos saltavam uns sobre os outros, e homem agarrava homem."
      ],
      notas: [
        { termo: "os escudos de umbigo", texto: "Escudos com uma saliência redonda no centro, que servia para desviar os golpes." }
      ]
    },
    {
      titulo: "Simoésio",
      versos: "473–489",
      linhas: [
        "Ali Ájax, filho de Télamon, matou o filho de Antémion,",
        "Simoésio, rapaz forte, que outrora a mãe dera à luz",
        "junto às margens do rio Simoente{1},",
        "quando descia do Ida, tendo ido com os pais ver os rebanhos;",
        "e por isso lhe chamaram Simoésio.",
        "Mas não pagou aos pais queridos o cuidado de o terem criado:",
        "curta foi a sua vida, derrubada pela lança de Ájax de grande ânimo.",
        "Ao avançar, à frente de todos, foi atingido no peito,",
        "junto ao mamilo direito; e a lança de bronze",
        "saiu-lhe pelo ombro, e ele caiu no chão, na poeira,",
        "como um choupo que cresceu na terra baixa de um grande brejo,",
        "liso, e com os ramos nascendo só bem no alto;",
        "um carpinteiro de carros corta-o com o ferro brilhante,",
        "para dobrar o aro de uma roda de um carro bonito,",
        "e ele fica a secar à beira do rio —",
        "assim Ájax, criado por Zeus, despojou",
        "Simoésio, filho de Antémion."
      ],
      notas: [
        { termo: "o rio Simoente", texto: "Um dos dois rios da planície de Troia, ao lado do Escamandro." }
      ]
    },
    {
      titulo: "Odisseu vinga o companheiro",
      versos: "490–516",
      linhas: [
        "Contra ele Antifo, de couraça brilhante, filho de Príamo,",
        "atirou a lança aguda por entre a multidão.",
        "Errou-o; mas acertou em Leuco, o bravo companheiro de Odisseu,",
        "na virilha, enquanto ele arrastava o morto para o outro lado.",
        "Caiu sobre o corpo, e o morto escorregou-lhe das mãos.",
        "Odisseu encheu-se de raiva no coração por aquela morte;",
        "avançou entre os primeiros combatentes, armado de bronze reluzente,",
        "chegou-se bem perto, olhou em volta",
        "e atirou a lança brilhante; e os troianos recuaram",
        "quando o homem atirou.",
        "Não lançou a lança à toa: acertou em Demócoon,",
        "filho bastardo{1} de Príamo, que viera de Abidos,",
        "das suas éguas velozes.",
        "A ele Odisseu, irado pelo companheiro, feriu com a lança na têmpora;",
        "e pela outra têmpora saiu a ponta de bronze;",
        "a escuridão lhe cobriu os olhos, e ele caiu com estrondo,",
        "e as armas retiniram sobre ele.",
        "Então recuaram os primeiros combatentes, e o glorioso Heitor;",
        "e os argivos gritaram bem alto, arrastaram os mortos",
        "e avançaram bem para a frente.",
        "Mas Apolo indignou-se, olhando de cima, de Pérgamo{2},",
        "e gritou alto para os troianos:",
        "“Levantai-vos, troianos domadores de cavalos,",
        "e não cedais o combate aos argivos!",
        "A carne deles não é de pedra nem de ferro,",
        "para aguentar o bronze que rasga a carne, quando são atingidos.",
        "E nem sequer Aquiles, filho de Tétis de belos cabelos, está a combater:",
        "junto às naves ele alimenta a ira que lhe come o coração.”"
      ],
      notas: [
        { termo: "filho bastardo", texto: "Filho de uma concubina. Em Homero esses filhos eram criados na casa do pai, mas ficavam abaixo dos legítimos." },
        { termo: "Pérgamo", texto: "A cidadela alta de Troia, onde ficavam os templos." }
      ]
    },
    {
      titulo: "Diores e Píroo",
      versos: "517–538",
      linhas: [
        "Assim falou da cidade o deus terrível.",
        "Mas aos aqueus incitava a filha de Zeus, a gloriosíssima Tritogênia{1},",
        "que percorria a multidão onde quer que os visse afrouxar.",
        "Então o destino prendeu Diores, filho de Amarinceu:",
        "foi atingido na perna direita por uma pedra pontuda,",
        "junto ao tornozelo; e quem a atirou foi o chefe dos trácios,",
        "Píroo, filho de Ímbraso, que viera de Eno.",
        "A pedra impiedosa esmagou de todo os tendões e os ossos;",
        "e ele caiu de costas na poeira, estendendo as duas mãos",
        "para os companheiros queridos, enquanto o ânimo lhe saía.",
        "Correu então aquele que o atingira, Píroo,",
        "e furou-o com a lança ao lado do umbigo;",
        "e todas as entranhas se lhe derramaram pelo chão,",
        "e a escuridão lhe cobriu os olhos.",
        "Mas Toante, o etólio, alcançou Píroo enquanto ele fugia,",
        "com a lança no peito, acima do mamilo,",
        "e o bronze cravou-se-lhe no pulmão.",
        "Toante chegou-se perto, arrancou-lhe do peito a lança poderosa,",
        "puxou a espada aguda e golpeou-o no meio do ventre,",
        "e tirou-lhe a vida.",
        "Mas não lhe tirou as armas, pois os companheiros o cercavam:",
        "trácios de cabelo no alto da cabeça{2}, segurando longas lanças,",
        "que o empurraram para trás, por maior e mais forte",
        "e mais altivo que ele fosse; e ele recuou, empurrado."
      ],
      notas: [
        { termo: "Tritogênia", texto: "Epíteto de Atena de sentido obscuro, já discutido na Antiguidade." },
        { termo: "trácios de cabelo no alto da cabeça", texto: "Os trácios prendiam o cabelo no alto da cabeça, penteado que os distinguia dos outros povos." }
      ]
    },
    {
      titulo: "Lado a lado na poeira",
      versos: "539–544",
      linhas: [
        "Assim ficaram estendidos lado a lado.",
        "E ali ninguém poderia falar com desdém daquele trabalho —",
        "nem mesmo quem, ainda sem ferida e sem golpe do bronze agudo,",
        "andasse pelo meio do combate,",
        "com Palas Atena a levá-lo pela mão",
        "e a afastar dele a chuva dos dardos;",
        "pois naquele dia muitos troianos e muitos aqueus",
        "ficaram estendidos lado a lado, de cara na poeira."
      ]
    }
  ]
});
