/* Ilíada — Canto IV
   Tradução em versos livres. */

window.ILIADA.cantos.push({
  numero: 4,
  romano: "IV",
  titulo: "A trégua quebrada",
  estrofes: [
    {
      titulo: "Os deuses bebem e discutem",
      versos: "1–19",
      linhas: [
        "Os deuses, sentados junto a Zeus, no soalho de ouro,",
        "estavam em assembleia; e entre eles a senhora Hebe{1}",
        "servia o néctar; e uns aos outros brindavam com taças de ouro,",
        "olhando para a cidade dos troianos.",
        "Logo o filho de Crono tentou provocar Hera",
        "com palavras ferinas, falando de lado:",
        "“Duas deusas são as protetoras de Menelau:",
        "Hera de Argos e Atena de Alalcômenas{2}.",
        "Mas essas ficam sentadas à parte, contentes de olhar;",
        "ao passo que Afrodite, amiga do riso, está sempre ao lado do outro",
        "e afasta dele as sortes da morte —",
        "e agora mesmo o salvou, quando ele já se julgava perdido.",
        "Mas a vitória é de Menelau, caro a Ares.",
        "Pensemos, pois, em como isto há de ficar:",
        "se havemos de acordar outra vez a guerra funesta",
        "e o estrondo terrível da batalha,",
        "ou de lançar amizade entre os dois lados.",
        "Se isso for bem-vindo e agradável a todos,",
        "a cidade do soberano Príamo poderia continuar habitada,",
        "e Menelau levaria de volta Helena de Argos.”"
      ],
      notas: [
        { termo: "Hebe", texto: "Filha de Zeus e de Hera, encarregada de servir a bebida dos deuses." },
        { termo: "Atena de Alalcômenas", texto: "Alalcômenas, cidade da Beócia onde Atena era cultuada." }
      ]
    },
    {
      titulo: "A ira de Hera",
      versos: "20–49",
      linhas: [
        "Assim falou; e Atena e Hera resmungaram,",
        "sentadas lado a lado, tramando males para os troianos.",
        "Atena ficou calada e nada disse, irritada com Zeus pai,",
        "e uma raiva selvagem a tomava;",
        "mas o peito de Hera não conteve a ira, e ela falou:",
        "“Terribilíssimo Cronida, que palavra disseste!",
        "Como podes querer tornar vão e sem efeito o meu trabalho,",
        "e o suor que suei na canseira? Os meus cavalos cansaram-se",
        "enquanto eu juntava o exército, trazendo desgraças",
        "a Príamo e aos filhos dele.",
        "Faze como quiseres; mas nem todos nós, os outros deuses, aprovamos.”",
        "Muito perturbado, respondeu-lhe Zeus que ajunta as nuvens:",
        "“Estranha! Que mal te fazem Príamo e os filhos de Príamo,",
        "para que te enfureças sem parar em arrasar",
        "a cidadela bem construída de Ílion?",
        "Se tu entrasses pelas portas e pelas longas muralhas",
        "e devorasses cru o próprio Príamo, e os filhos de Príamo,",
        "e os outros troianos, talvez então curasses essa tua ira.",
        "Faze como te aprouver; que esta briga, mais tarde,",
        "não venha a ser entre nós motivo de grande contenda.",
        "Mas outra coisa te digo, e guarda-a no teu ânimo:",
        "quando também eu quiser destruir alguma cidade",
        "onde nasçam homens que te sejam caros,",
        "não travarás a minha ira: deixa-me fazer —",
        "pois esta eu te dei de boa vontade, mas com o coração contra.",
        "De todas as cidades que há sob o sol e o céu estrelado,",
        "onde moram os homens que habitam a terra,",
        "a sagrada Ílion era a mais honrada no meu coração,",
        "e Príamo, e o povo de Príamo da boa lança de freixo.",
        "Pois nunca faltou ao meu altar a parte igual do banquete,",
        "a libação e o cheiro da gordura:",
        "foi essa a porção que nos coube por direito.”"
      ]
    },
    {
      titulo: "As três cidades de Hera",
      versos: "50–67",
      linhas: [
        "Respondeu-lhe então a soberana Hera de olhos de novilha:",
        "“Três cidades me são de longe as mais queridas:",
        "Argos, Esparta e Micenas de largas ruas.",
        "Arrasa-as quando elas se tornarem odiosas ao teu coração;",
        "eu não me porei diante delas, nem te farei oposição.",
        "Ainda que eu tivesse ciúme e não te deixasse destruí-las,",
        "nada conseguiria, pois tu és de longe o mais forte.",
        "Mas também o meu trabalho não pode ficar sem efeito:",
        "também eu sou deusa, e a minha origem é a mesma que a tua;",
        "Crono de curvos conselhos gerou-me a mais honrada,",
        "tanto pelo nascimento como por ser chamada tua mulher —",
        "e tu reinas sobre todos os imortais.",
        "Mas cedamos nisto um ao outro, eu a ti e tu a mim;",
        "e os outros deuses imortais nos seguirão.",
        "Manda depressa Atena ao estrondo terrível",
        "dos troianos e dos aqueus,",
        "e que ela faça com que sejam os troianos os primeiros",
        "a fazer mal aos aqueus gloriosos, contra os juramentos.”"
      ]
    },
    {
      titulo: "Atena desce como uma estrela",
      versos: "68–84",
      linhas: [
        "Assim falou; e o pai dos homens e dos deuses não desobedeceu.",
        "Logo disse a Atena palavras aladas:",
        "“Vai depressa ao exército, entre troianos e aqueus,",
        "e faze com que sejam os troianos os primeiros",
        "a fazer mal aos aqueus gloriosos, contra os juramentos.”",
        "Assim dizendo, incitou Atena, que já estava disposta;",
        "e ela desceu num salto dos cumes do Olimpo.",
        "Como o filho de Crono de curvos conselhos manda uma estrela,",
        "presságio para os navegantes ou para um largo exército de homens,",
        "brilhante, e dela saltam muitas faíscas:",
        "assim Palas Atena se atirou à terra e caiu no meio deles;",
        "e o espanto tomou os que viam —",
        "os troianos domadores de cavalos e os aqueus de belas grevas.",
        "E assim dizia um, olhando para o vizinho:",
        "“Ou vamos ter outra vez a guerra funesta",
        "e o estrondo terrível da batalha,",
        "ou Zeus põe amizade entre os dois lados —",
        "ele, que é o despenseiro da guerra dos homens.”"
      ]
    },
    {
      titulo: "Atena tenta Pândaro",
      versos: "85–103",
      linhas: [
        "Assim dizia um, entre aqueus e troianos.",
        "Mas ela entrou no meio da multidão dos troianos",
        "com a figura de um homem, Laódoco, filho de Antenor,",
        "forte com a lança, à procura do divino Pândaro.",
        "Encontrou parado o filho de Licáon, irrepreensível e forte,",
        "e em volta dele as fileiras cerradas dos que trazem escudo,",
        "os que o tinham seguido desde as correntes do Esepo.",
        "Pondo-se a seu lado, disse-lhe palavras aladas:",
        "“Deixarias tu convencer-te por mim, sábio filho de Licáon?",
        "Terias então a coragem de atirar uma flecha rápida em Menelau,",
        "e ganharias agradecimento e glória entre todos os troianos,",
        "e sobretudo diante do príncipe Alexandre.",
        "Dele, antes de todos, receberias com certeza presentes esplêndidos,",
        "se ele visse Menelau, o guerreiro filho de Atreu,",
        "abatido pela tua seta e posto sobre a pira dolorosa.",
        "Vamos, atira no glorioso Menelau,",
        "e promete a Apolo, o nascido do lobo{1}, glorioso com o arco,",
        "sacrificar uma famosa hecatombe de cordeiros primogênitos,",
        "quando voltares para casa, para a cidade sagrada de Zeleia.”"
      ],
      notas: [
        { termo: "o nascido do lobo", texto: "Epíteto obscuro de Apolo: pode significar “nascido do lobo” ou “nascido na Lícia”." }
      ]
    },
    {
      titulo: "O arco de chifre",
      versos: "104–126",
      linhas: [
        "Assim falou Atena, e convenceu-lhe o ânimo insensato.",
        "Logo ele descobriu o arco polido, feito do chifre",
        "de um bode selvagem que ele próprio, uma vez, atingira no peito,",
        "à espreita num esconderijo, quando o animal descia de uma rocha:",
        "acertou-lhe no peito, e ele caiu para trás, sobre a pedra.",
        "Da cabeça dele saíam chifres de dezesseis palmos;",
        "o artífice do chifre uniu-os e ajustou-os,",
        "alisou tudo com cuidado e pôs-lhe uma ponta de ouro.",
        "Pândaro armou o arco, dobrando-o bem,",
        "e pousou-o encostado ao chão; e os companheiros valentes",
        "puseram os escudos diante dele,",
        "para que os filhos guerreiros dos aqueus não se levantassem",
        "antes de ser atingido Menelau, o guerreiro filho de Atreu.",
        "Tirou a tampa da aljava e escolheu uma flecha,",
        "emplumada, nunca disparada, portadora de dores negras.",
        "Depressa ajustou a seta amarga à corda,",
        "e prometeu a Apolo, o nascido do lobo, glorioso com o arco,",
        "sacrificar uma famosa hecatombe de cordeiros primogênitos,",
        "quando voltasse para casa, para a cidade sagrada de Zeleia.",
        "Puxou, segurando juntos o entalhe e a corda de tendão de boi;",
        "trouxe a corda ao peito e a ponta de ferro ao arco.",
        "E quando dobrou o grande arco em círculo,",
        "o arco rangeu, a corda cantou alto,",
        "e a seta aguda saltou, ansiosa por voar para dentro da multidão."
      ]
    },
    {
      titulo: "A flecha desviada",
      versos: "127–147",
      linhas: [
        "Mas os deuses bem-aventurados não se esqueceram de ti, Menelau —",
        "antes de todos a filha de Zeus, a que arrasta despojos,",
        "que se pôs diante de ti e desviou a seta aguda.",
        "Afastou-a da carne como a mãe enxota uma mosca do filho",
        "quando ele dorme um sono doce;",
        "e ela própria a guiou para onde as fivelas de ouro do cinto",
        "se prendiam, e a couraça se fazia dupla.",
        "A seta amarga caiu sobre o cinto bem ajustado;",
        "atravessou o cinto lavrado,",
        "forçou caminho pela couraça bem trabalhada",
        "e pela proteção que ele usava para resguardar a carne,",
        "barreira contra os dardos, que mais o protegia —",
        "e ainda assim passou também por ela.",
        "A flecha roçou a pele mais externa do homem,",
        "e logo o sangue escuro corria da ferida.",
        "Como quando uma mulher da Meônia ou da Cária",
        "tinge marfim de púrpura, para servir de peça de face aos cavalos:",
        "fica guardado numa câmara, e muitos cavaleiros",
        "desejam levá-lo, mas ele fica como tesouro de um rei,",
        "ao mesmo tempo enfeite do cavalo e glória do condutor —",
        "assim, Menelau, se tingiram de sangue as tuas coxas,",
        "as coxas bem-feitas, e as pernas, e os belos tornozelos por baixo."
      ]
    },
    {
      titulo: "O juramento pisado",
      versos: "148–168",
      linhas: [
        "Estremeceu então Agamêmnon, soberano de homens,",
        "ao ver o sangue escuro correr da ferida;",
        "e estremeceu também o próprio Menelau, caro a Ares.",
        "Mas quando viu que o tendão e as farpas estavam fora da carne,",
        "o ânimo voltou a juntar-se-lhe no peito.",
        "Gemendo fundo, falou entre eles o soberano Agamêmnon,",
        "segurando Menelau pela mão, e os companheiros gemiam com ele:",
        "“Irmão querido, foi para a tua morte que eu jurei os juramentos,",
        "pondo-te sozinho diante dos aqueus a combater os troianos,",
        "já que os troianos te alvejaram e pisaram os juramentos fiéis.",
        "Mas o juramento não é em vão, nem o sangue dos cordeiros,",
        "nem as libações puras, nem os apertos de mão em que confiamos.",
        "Pois ainda que o Olímpio não o cumpra já,",
        "há de cumpri-lo tarde; e eles pagarão caro,",
        "com as próprias cabeças, e com as mulheres e os filhos.",
        "Isto eu bem sei, no espírito e no coração:",
        "virá um dia em que há de perecer a sagrada Ílion,",
        "e Príamo, e o povo de Príamo da boa lança de freixo;",
        "e Zeus, filho de Crono, sentado no alto, que habita o céu,",
        "há de sacudir sobre todos eles a égide escura,",
        "irado com este engano. Isto não ficará por cumprir.”"
      ]
    },
    {
      titulo: "O chamado ao curador",
      versos: "169–197",
      linhas: [
        "“Mas terei uma dor terrível por ti, Menelau,",
        "se morreres e cumprires a medida da tua vida.",
        "E eu voltaria coberto de vergonha para Argos sedenta,",
        "pois logo os aqueus se lembrariam da terra dos pais,",
        "e deixaríamos a Príamo e aos troianos, como troféu,",
        "Helena de Argos; e os teus ossos apodreceriam",
        "enquanto jazesses em Troia, com a obra por acabar.",
        "E assim diria algum troiano arrogante,",
        "saltando sobre o túmulo do glorioso Menelau:",
        "‘Que Agamêmnon cumpra sempre assim a sua ira,",
        "como agora, que trouxe para cá um exército de aqueus à toa",
        "e voltou para a terra amada dos pais com as naves vazias,",
        "deixando para trás o nobre Menelau.’",
        "Assim há de dizer alguém; e então que a terra larga se abra para mim.”",
        "Mas Menelau de louros cabelos animou-o:",
        "“Coragem, e não assustes ainda o exército dos aqueus.",
        "A seta aguda não se cravou em lugar mortal:",
        "deteve-a antes o cinto brilhante, e por baixo",
        "a saia de metal e a proteção que os ferreiros fizeram.”",
        "Respondendo-lhe, disse o soberano Agamêmnon:",
        "“Oxalá seja assim, Menelau querido.",
        "Mas um curador há de tratar a ferida",
        "e pôr-lhe remédios que façam parar as dores negras.”",
        "Assim falou, e dirigiu-se a Taltíbio, o arauto divino:",
        "“Taltíbio, chama aqui, o mais depressa que puderes, Macáon,",
        "filho de Asclépio{1}, o curador irrepreensível,",
        "para ver o guerreiro Menelau, filho de Atreu,",
        "que alguém entendido no arco alvejou —",
        "um troiano ou um lício —, glória para ele, e dor para nós.”"
      ],
      notas: [
        { termo: "Asclépio", texto: "Grande curandeiro, pai de Macáon; mais tarde passou a ser cultuado como o deus da medicina." }
      ]
    },
    {
      titulo: "Macáon trata a ferida",
      versos: "198–219",
      linhas: [
        "Assim falou; e o arauto não desobedeceu ao ouvi-lo.",
        "Foi pelo exército dos aqueus vestidos de bronze,",
        "à procura do herói Macáon. Encontrou-o parado,",
        "e em volta dele as fileiras cerradas dos que trazem escudo,",
        "os que o tinham seguido de Trica, pastagem de cavalos.",
        "Pondo-se a seu lado, disse-lhe palavras aladas:",
        "“Levanta-te, filho de Asclépio! Chama-te o soberano Agamêmnon,",
        "para veres o guerreiro Menelau, chefe dos aqueus,",
        "que alguém entendido no arco alvejou —",
        "um troiano ou um lício —, glória para ele, e dor para nós.”",
        "Assim falou, e mexeu-lhe com o coração no peito.",
        "Foram os dois pela multidão, ao longo do largo exército dos aqueus.",
        "E quando chegaram ao lugar onde estava ferido Menelau de louros cabelos,",
        "e todos os chefes reunidos em roda dele,",
        "o homem divino veio para o meio deles;",
        "e logo puxou a flecha do cinto bem ajustado,",
        "e, ao ser puxada, as farpas agudas partiram-se para trás.",
        "Soltou o cinto brilhante e, por baixo,",
        "a saia de metal e a proteção que os ferreiros fizeram.",
        "Quando viu a ferida onde caíra a seta amarga,",
        "chupou o sangue e espalhou por cima, com perícia,",
        "remédios que acalmam, os que outrora Quíron{1}, por amizade,",
        "tinha dado ao pai dele."
      ],
      notas: [
        { termo: "Quíron", texto: "O centauro que criou e instruiu vários heróis, entre eles Aquiles, e era mestre na arte de curar." }
      ]
    }
  ]
});
