/* Ilíada — Canto II
   Traduzido, exceto os dois catálogos, apresentados em resumo no lugar em que ocorrem.
   Páginas com "paragrafos" (em vez de "linhas") são resumos em prosa. */

window.ILIADA.cantos.push({
  numero: 2,
  romano: "II",
  titulo: "O sonho e a prova do exército",
  estrofes: [
    {
      titulo: "O Sonho enganoso",
      versos: "1–15",
      linhas: [
        "Os outros deuses e os homens de carros empenachados",
        "dormiram a noite inteira; mas a Zeus o sono doce não prendia:",
        "revolvia no espírito como havia de honrar Aquiles",
        "e fazer perecer muitos junto às naves dos aqueus.",
        "E este plano lhe pareceu, no ânimo, o melhor:",
        "mandar a Agamêmnon, filho de Atreu, um Sonho{1} funesto.",
        "Dirigindo-se a ele, disse palavras aladas:",
        "“Vai, Sonho funesto, às naves velozes dos aqueus;",
        "entra na tenda de Agamêmnon, filho de Atreu,",
        "e dize-lhe tudo, exatamente como eu te ordeno.",
        "Manda que arme depressa os aqueus de longos cabelos,",
        "pois agora poderá tomar a cidade de largas ruas dos troianos:",
        "já não estão divididos os imortais que habitam o Olimpo,",
        "pois Hera a todos dobrou com a sua súplica,",
        "e sobre os troianos pesam desgraças.”"
      ],
      notas: [
        { termo: "um Sonho", texto: "Para Homero o sonho é uma figura que vem de fora, enviada por um deus, e não algo que nasce de dentro de quem dorme." }
      ]
    },
    {
      titulo: "A mensagem entregue",
      versos: "16–34",
      linhas: [
        "Assim falou; e o Sonho partiu, depois de ouvir a ordem.",
        "Depressa chegou às naves velozes dos aqueus",
        "e foi ter com Agamêmnon, filho de Atreu. Encontrou-o",
        "dormindo na tenda, envolto em sono divino.",
        "Pôs-se junto à cabeça dele, tomando a figura do filho de Neleu,",
        "Nestor, o ancião que Agamêmnon mais honrava entre todos;",
        "e, com essa aparência, disse o Sonho divino:",
        "“Dormes, filho do prudente Atreu, domador de cavalos?",
        "Não deve dormir a noite inteira um homem de conselho,",
        "a quem o povo está confiado e que tem tantos cuidados.",
        "Agora escuta-me depressa: sou mensageiro de Zeus,",
        "que, mesmo de longe, muito cuida de ti e tem pena de ti.",
        "Manda que armes depressa os aqueus de longos cabelos,",
        "pois agora poderás tomar a cidade de largas ruas dos troianos:",
        "já não estão divididos os imortais que habitam o Olimpo,",
        "pois Hera a todos dobrou com a sua súplica,",
        "e sobre os troianos pesam desgraças, por vontade de Zeus.",
        "Guarda isto no coração, e que o esquecimento não te tome",
        "quando te largar o sono doce como o mel.”"
      ]
    },
    {
      titulo: "O rei se prepara",
      versos: "35–47",
      linhas: [
        "Assim dizendo, partiu, e deixou-o ali a pensar no coração",
        "coisas que não haviam de cumprir-se:",
        "julgava tomar a cidade de Príamo naquele mesmo dia.",
        "Insensato! Não sabia o que Zeus planejava,",
        "que ainda ia impor dores e gemidos",
        "a troianos e a dânaos, em combates duros.",
        "Acordou do sono, com a voz divina em volta dele.",
        "Sentou-se, vestiu a túnica macia, bela e nova,",
        "lançou sobre ela o grande manto e atou aos pés luzentes",
        "as belas sandálias; pendurou aos ombros a espada de prata cravejada,",
        "tomou o cetro dos pais, imperecível para sempre,",
        "e com ele foi às naves dos aqueus vestidos de bronze."
      ]
    },
    {
      titulo: "O conselho dos anciãos",
      versos: "48–70",
      linhas: [
        "A Aurora subia ao alto Olimpo,",
        "anunciando a luz a Zeus e aos outros imortais.",
        "E ele mandou que os arautos de voz clara",
        "convocassem à assembleia os aqueus de longos cabelos.",
        "Convocaram, e os homens juntaram-se depressa.",
        "Primeiro, porém, reuniu em conselho os anciãos de grande ânimo,",
        "junto à nave de Nestor, o rei nascido em Pilos.",
        "Tendo-os reunido, expôs-lhes um plano astuto:",
        "“Ouvi-me, amigos: veio ter comigo, no sono, um Sonho divino,",
        "através da noite imortal, muito parecido com o nobre Nestor",
        "na figura, no tamanho e no porte.",
        "Pôs-se junto à minha cabeça e disse-me:",
        "‘Dormes, filho do prudente Atreu, domador de cavalos?",
        "Não deve dormir a noite inteira um homem de conselho,",
        "a quem o povo está confiado e que tem tantos cuidados.",
        "Agora escuta-me depressa: sou mensageiro de Zeus,",
        "que, mesmo de longe, muito cuida de ti e tem pena de ti.",
        "Manda que armes depressa os aqueus de longos cabelos,",
        "pois agora poderás tomar a cidade de largas ruas dos troianos:",
        "já não estão divididos os imortais que habitam o Olimpo,",
        "pois Hera a todos dobrou com a sua súplica,",
        "e sobre os troianos pesam desgraças, por vontade de Zeus.",
        "Guarda isto no coração.’ Assim falando, voou-se embora,",
        "e o sono doce largou-me.”"
      ]
    },
    {
      titulo: "A prova proposta",
      versos: "71–83",
      linhas: [
        "“Vamos, vejamos se conseguimos armar os filhos dos aqueus.",
        "Mas primeiro, como é de direito, hei de prová-los com palavras:",
        "mandarei que fujam com as naves de muitos bancos,",
        "e vós, de um lado e de outro, contende-os com palavras.”",
        "Assim falou, e sentou-se. Então ergueu-se entre eles",
        "Nestor, que era rei da arenosa Pilos.",
        "Com bom ânimo, assim lhes falou:",
        "“Amigos, chefes e guias dos argivos:",
        "se outro qualquer dos aqueus nos contasse esse sonho,",
        "diríamos que era mentira, e ainda nos afastaríamos dele.",
        "Mas viu-o aquele que se gaba de ser o melhor entre os aqueus.",
        "Vamos, pois: vejamos se conseguimos armar os filhos dos aqueus.”",
        "Assim dizendo, saiu à frente do conselho."
      ]
    },
    {
      titulo: "A assembleia se reúne",
      versos: "84–100",
      linhas: [
        "Levantaram-se e seguiram-no os reis portadores do cetro,",
        "e o povo acorria. Como saem os enxames de abelhas,",
        "em multidão, de uma rocha oca, sempre em levas novas,",
        "e voam em cachos sobre as flores da primavera,",
        "umas para um lado, outras para outro:",
        "assim as muitas tribos de homens, vindas das naves e das tendas,",
        "marchavam em bandos, ao longo da praia funda, para a assembleia.",
        "Entre eles ardia o Boato{1}, mensageiro de Zeus, incitando-os a ir;",
        "e eles juntavam-se.",
        "A assembleia estava em alvoroço; a terra gemia por baixo,",
        "enquanto o povo se sentava, e havia grande estrondo.",
        "Nove arautos, gritando, tentavam contê-los,",
        "para que cessassem o clamor e ouvissem os reis criados por Zeus.",
        "A custo o povo se sentou e ficou nos seus lugares,",
        "parando de fazer barulho."
      ],
      notas: [
        { termo: "o Boato", texto: "A notícia que corre sozinha por um acampamento, tratada como um ser vivo e mensageiro de Zeus." }
      ]
    },
    {
      titulo: "O cetro e a palavra do rei",
      versos: "101–118",
      linhas: [
        "Ergueu-se então o soberano Agamêmnon, segurando o cetro{1}",
        "que Hefesto trabalhara com arte.",
        "Hefesto deu-o ao soberano Zeus, filho de Crono;",
        "Zeus deu-o ao mensageiro matador de Argos{2};",
        "e o soberano Hermes deu-o a Pélops, tocador de cavalos;",
        "Pélops, por sua vez, deu-o a Atreu, pastor de povos;",
        "Atreu, ao morrer, deixou-o a Tiestes, rico em rebanhos;",
        "e Tiestes deixou-o a Agamêmnon, para que o levasse",
        "e reinasse sobre muitas ilhas e sobre toda a Argos.",
        "Apoiado nesse cetro, falou aos argivos:",
        "“Amigos, heróis dânaos, servidores de Ares:",
        "Zeus, filho de Crono, prendeu-me numa cegueira pesada.",
        "Cruel! Antes me prometeu e acenou com a cabeça",
        "que eu havia de arrasar Ílion de boas muralhas e voltar;",
        "mas agora planejou um engano funesto e manda-me",
        "regressar a Argos sem honra, depois de perder tantos homens."
      ],
      notas: [
        { termo: "o cetro", texto: "O cetro de Agamêmnon passa de Hefesto a Zeus e daí, de herdeiro em herdeiro, até ele: é a prova material do seu direito de mandar." },
        { termo: "o mensageiro matador de Argos", texto: "Hermes, o mensageiro dos deuses. O epíteto vem de ter matado Argos, o gigante de cem olhos." }
      ]
    },
    {
      titulo: "“Fujamos para casa”",
      versos: "119–141",
      linhas: [
        "“Assim, ao que parece, apraz a Zeus poderosíssimo,",
        "que já derrubou o alto de muitas cidades e ainda há de derrubar,",
        "pois o poder dele é o maior de todos.",
        "Vergonhoso será ouvirem isto os homens que vierem depois:",
        "que um exército aqueu tão grande e tão bom",
        "fez uma guerra inútil e combateu contra menos homens,",
        "sem que se veja fim nenhum.",
        "Pois se quiséssemos, aqueus e troianos,",
        "jurar fidelidade e contar-nos uns aos outros —",
        "os troianos juntando todos os que têm casa na cidade,",
        "e nós, aqueus, dispostos em grupos de dez,",
        "e cada grupo escolhendo um troiano para servir o vinho —,",
        "muitos grupos de dez ficariam sem quem lhes servisse{1}:",
        "tanto os filhos dos aqueus são mais numerosos",
        "do que os troianos que moram na cidade.",
        "Mas há aliados vindos de muitas cidades, homens de lança,",
        "e são eles que me atrapalham e não me deixam",
        "saquear a cidadela bem povoada de Ílion.",
        "Já se passaram nove anos do grande Zeus:",
        "a madeira das naves apodreceu, as cordas afrouxaram,",
        "e as nossas mulheres e os filhos pequenos",
        "estão sentados nas casas à nossa espera; e a obra",
        "para que viemos continua por fazer.",
        "Vamos, obedeçamos todos ao que eu digo:",
        "fujamos com as naves para a terra amada dos pais,",
        "pois já não havemos de tomar Troia de largas ruas.”"
      ],
      notas: [
        { termo: "muitos grupos de dez ficariam sem quem lhes servisse", texto: "A conta é um modo de dizer que os gregos são muito mais numerosos: se cada dez aqueus tomassem um troiano para lhes servir o vinho, sobrariam grupos sem copeiro." }
      ]
    },
    {
      titulo: "A debandada",
      versos: "142–154",
      linhas: [
        "Assim falou; e comoveu o coração no peito de toda a multidão",
        "que não tinha ouvido o plano.",
        "A assembleia agitou-se como as ondas longas do mar Icário,",
        "quando o vento leste e o vento sul as levantam,",
        "caindo das nuvens de Zeus pai.",
        "E como quando o vento oeste chega e sacode uma seara alta,",
        "soprando com força, e as espigas se curvam:",
        "assim se agitou toda aquela assembleia.",
        "Com um grito correram para as naves; e a poeira,",
        "debaixo dos pés, subia e ficava suspensa no ar.",
        "Gritavam uns para os outros que pegassem nas naves",
        "e as arrastassem para o mar divino; limpavam os canais de lançamento,",
        "e o clamor dos que queriam voltar para casa subia ao céu;",
        "e tiravam as escoras de baixo dos navios."
      ]
    },
    {
      titulo: "Hera manda Atena",
      versos: "155–181",
      linhas: [
        "E ali os argivos teriam tido um regresso fora do destino{1},",
        "se Hera não dissesse a Atena:",
        "“Ai, filha de Zeus porta-égide, incansável!",
        "Então os argivos hão de fugir assim para casa,",
        "pelo dorso largo do mar,",
        "e deixar a Príamo e aos troianos, como troféu,",
        "Helena de Argos, por quem tantos aqueus morreram em Troia,",
        "longe da terra dos pais?",
        "Vai agora pelo exército dos aqueus vestidos de bronze;",
        "com as tuas palavras brandas detém cada homem,",
        "e não deixes que arrastem para o mar as naves recurvas.”",
        "Assim falou; e a deusa Atena de olhos brilhantes não desobedeceu.",
        "Desceu num salto dos cumes do Olimpo",
        "e depressa chegou às naves velozes dos aqueus.",
        "Encontrou Odisseu, igual a Zeus no conselho, parado:",
        "não tinha posto a mão na sua nave negra de bons bancos,",
        "pois a dor lhe chegara ao coração e ao ânimo.",
        "Pondo-se a seu lado, disse Atena de olhos brilhantes:",
        "“Filho de Laertes, criado por Zeus, Odisseu de muitos recursos:",
        "então haveis de lançar-vos às naves de muitos bancos",
        "e fugir para casa?",
        "E deixareis a Príamo e aos troianos, como troféu,",
        "Helena de Argos, por quem tantos aqueus morreram em Troia?",
        "Vai agora pelo exército e detém cada homem",
        "com as tuas palavras brandas; não deixes que arrastem para o mar",
        "as naves recurvas.”"
      ],
      notas: [
        { termo: "um regresso fora do destino", texto: "Homero admite que os acontecimentos possam sair do destino traçado; é para impedir isso que os deuses intervêm." }
      ]
    },
    {
      titulo: "Odisseu contém o exército",
      versos: "182–210",
      linhas: [
        "Reconheceu ele a voz da deusa e pôs-se a correr,",
        "largando o manto, que o arauto Euríbates recolheu.",
        "Foi ao encontro de Agamêmnon, filho de Atreu, e recebeu dele",
        "o cetro dos pais, imperecível para sempre;",
        "e com ele percorreu as naves dos aqueus vestidos de bronze.",
        "A cada rei, ou homem de nome, que encontrava,",
        "punha-se a seu lado e o continha com palavras brandas:",
        "“Amigo, não fica bem assustar-te como a um covarde.",
        "Senta-te tu, e faze sentar também os outros.",
        "Ainda não sabes ao certo o que pensa o Atrida:",
        "agora está a pôr-nos à prova, e logo há de castigar os aqueus.",
        "No conselho, nem todos ouvimos o que ele disse?",
        "Cuidado, não vá ele, irado, fazer mal aos filhos dos aqueus.",
        "Grande é a ira de um rei criado por Zeus:",
        "a honra dele vem de Zeus, e Zeus de bom conselho o ama.”",
        "Mas quando via um homem do povo, e o encontrava aos gritos,",
        "batia-lhe com o cetro e repreendia-o:",
        "“Fica sentado e escuta a palavra dos outros,",
        "que são melhores do que tu; tu não prestas para a guerra",
        "nem tens força, e não contas nem no combate nem no conselho.",
        "De modo nenhum havemos de ser reis todos nós, aqueus.",
        "Não é bom o governo de muitos: haja um só chefe,",
        "um só rei, a quem o filho de Crono de curvos conselhos",
        "deu o cetro e as sentenças, para que decida pelo seu povo.”"
      ]
    },
    {
      titulo: "Tersites",
      versos: "211–242",
      linhas: [
        "Assim percorria o exército, pondo-o em ordem. E eles voltavam",
        "das naves e das tendas para a assembleia, com barulho,",
        "como quando a onda do mar de muito estrondo",
        "ribomba na praia longa, e o alto-mar retumba.",
        "Os outros sentaram-se e ficaram nos seus lugares;",
        "só Tersites{1}, de fala sem medida, ainda tagarelava —",
        "ele, que sabia no peito muitas palavras desordenadas,",
        "boas para brigar com os reis à toa e fora de hora,",
        "desde que parecessem engraçadas aos argivos.",
        "Era o homem mais feio que chegou a Ílion:",
        "tinha as pernas tortas e era coxo de um pé;",
        "os ombros corcundas fechavam-se-lhe sobre o peito;",
        "em cima, a cabeça era pontuda, e nela crescia um cabelo ralo.",
        "Era o mais odiado por Aquiles e por Odisseu,",
        "pois costumava insultá-los. Agora, com gritos agudos,",
        "lançava injúrias contra o divino Agamêmnon;",
        "e os aqueus, indignados, tinham raiva dele.",
        "Gritando bem alto, insultava assim Agamêmnon:",
        "“Atrida, de que te queixas agora? De que precisas?",
        "As tuas tendas estão cheias de bronze, e nelas há muitas mulheres",
        "escolhidas, que nós, aqueus, te damos primeiro, sempre",
        "que tomamos alguma cidadela.",
        "Ou ainda te falta ouro, que algum troiano domador de cavalos",
        "traga de Ílion como resgate do filho",
        "que eu, ou outro aqueu, tenha amarrado e levado?",
        "Ou uma mulher nova, para deitar-te com ela",
        "e guardá-la só para ti?",
        "Não fica bem que um chefe leve os filhos dos aqueus à desgraça.",
        "Covardes, criaturas vergonhosas — aqueias, e não aqueus!",
        "Voltemos para casa com as naves, e deixemos este homem aqui,",
        "em Troia, a digerir os seus prêmios,",
        "para que veja se lhe servimos de alguma coisa ou não.",
        "Ele agora desonrou Aquiles, homem muito melhor do que ele:",
        "tomou-lhe o prêmio e o retém, tendo-o arrancado ele próprio.",
        "Mas não há ira no coração de Aquiles: ele deixa correr —",
        "senão, Atrida, esta seria a tua última afronta.”"
      ],
      notas: [
        { termo: "Tersites", texto: "O único homem do exército que Homero descreve como feio. Não é rei nem chefe: é um soldado comum." }
      ]
    },
    {
      titulo: "A pancada do cetro",
      versos: "243–277",
      linhas: [
        "Assim falou Tersites, insultando Agamêmnon, pastor de povos.",
        "Depressa veio ter com ele o divino Odisseu",
        "e, olhando-o de través, repreendeu-o com palavras duras:",
        "“Tersites de fala desatinada, orador de voz clara — cala-te,",
        "e não queiras brigar sozinho contra os reis.",
        "Digo-te que não há homem pior do que tu",
        "entre todos os que vieram com os Atridas para Ílion.",
        "Portanto não tomes na boca o nome dos reis,",
        "nem lhes atires injúrias, nem fiques à espreita do regresso.",
        "Ainda não sabemos ao certo como isto vai acabar,",
        "nem se voltaremos bem ou mal, nós, filhos dos aqueus.",
        "Mas isto eu te digo, e há de cumprir-se:",
        "se eu te apanhar outra vez a fazer o palhaço como agora,",
        "que a cabeça de Odisseu não fique mais sobre os seus ombros,",
        "nem me chamem mais pai de Telêmaco{1},",
        "se eu não te agarrar, e te arrancar a roupa —",
        "o manto, a túnica e o que te cobre a nudez —,",
        "e não te mandar chorando para as naves velozes,",
        "escorraçado da assembleia com pancadas humilhantes.”",
        "Assim falou, e bateu-lhe com o cetro nas costas e nos ombros.",
        "Ele dobrou-se, e uma lágrima grossa lhe caiu;",
        "um vergão de sangue subiu-lhe nas costas, por baixo do cetro de ouro.",
        "Sentou-se com medo, dolorido, e, olhando à toa,",
        "limpou a lágrima. Os outros, embora aborrecidos,",
        "riram-se dele com gosto; e assim dizia um, olhando para o vizinho:",
        "“Ora! Muitas coisas boas já fez Odisseu,",
        "dando bons conselhos e organizando a guerra;",
        "mas isto agora é de longe o melhor que ele fez entre os argivos:",
        "calou este atirador de palavras, este caluniador.",
        "Não há de o ânimo atrevido levá-lo outra vez",
        "a insultar os reis com palavras de afronta.”"
      ],
      notas: [
        { termo: "Telêmaco", texto: "O filho de Odisseu, deixado recém-nascido em Ítaca quando o pai partiu para a guerra." }
      ]
    },
    {
      titulo: "Odisseu fala ao exército",
      versos: "278–300",
      linhas: [
        "Assim dizia a multidão. Então ergueu-se Odisseu, destruidor de cidades,",
        "segurando o cetro; e ao lado dele Atena de olhos brilhantes,",
        "tomando a figura de um arauto, mandou o exército calar-se,",
        "para que ouvissem as suas palavras, ao mesmo tempo,",
        "os que estavam perto e os que estavam longe,",
        "e todos pudessem pensar no conselho.",
        "Com bom ânimo, assim lhes falou:",
        "“Atrida, os aqueus querem agora tornar-te",
        "o mais desprezado entre todos os homens mortais,",
        "e não te cumprem a promessa que fizeram ao vir para cá,",
        "de Argos criadora de cavalos:",
        "que só voltariam depois de arrasar Ílion de boas muralhas.",
        "Como crianças pequenas, ou mulheres viúvas,",
        "choram uns para os outros, querendo voltar para casa.",
        "É verdade que é duro partir daqui abatido.",
        "Já quem fica um mês longe da mulher se irrita",
        "junto à nave de bons bancos, quando as tempestades do inverno",
        "e o mar revolto o prendem.",
        "E a nós já é o nono ano que se cumpre, enquanto ficamos aqui.",
        "Por isso não censuro os aqueus por se aborrecerem",
        "junto às naves recurvas.",
        "Mas, ainda assim, é vergonhoso esperar tanto tempo",
        "e voltar de mãos vazias.",
        "Aguentai, amigos, e ficai mais um pouco, até sabermos",
        "se Calcas profetiza a verdade ou não.”"
      ]
    },
    {
      titulo: "O presságio de Áulis",
      versos: "301–332",
      linhas: [
        "“Pois isto sabemos bem no coração, e sois todos testemunhas —",
        "vós, a quem as sortes da morte ainda não levaram.",
        "Foi ontem, ou anteontem, quando as naves dos aqueus",
        "se juntavam em Áulis{1}, trazendo desgraças a Príamo e aos troianos,",
        "e nós, em volta de uma fonte, oferecíamos aos imortais",
        "hecatombes perfeitas sobre altares sagrados,",
        "debaixo de um belo plátano de onde corria água clara.",
        "Apareceu então um grande sinal: uma serpente de dorso vermelho,",
        "terrível, que o próprio Olímpio fizera vir à luz,",
        "saiu de baixo do altar e foi ter ao plátano.",
        "Ali estavam as crias de um pardal, filhotes tenros,",
        "no ramo mais alto, encolhidos debaixo das folhas:",
        "eram oito, e a mãe que os gerara fazia nove.",
        "A serpente devorou-os enquanto eles piavam de dor;",
        "e a mãe esvoaçava em volta, chorando os filhos queridos.",
        "Ela enroscou-se e apanhou-a por uma asa, enquanto gritava.",
        "Depois de devorar as crias do pardal e a própria mãe,",
        "o deus que a mostrara tornou-a um sinal:",
        "o filho de Crono de curvos conselhos transformou-a em pedra;",
        "e nós ficamos parados, espantados com aquilo.",
        "Assim, quando o presságio terrível entrou no meio dos sacrifícios,",
        "Calcas logo profetizou:",
        "‘Por que estais calados, aqueus de longos cabelos?",
        "Zeus de bom conselho mostrou-nos este grande sinal,",
        "tardio a chegar e tardio a cumprir-se,",
        "cuja fama nunca há de perecer.",
        "Assim como esta serpente devorou as crias do pardal e a mãe —",
        "oito, e a mãe que os gerara fazia nove —,",
        "assim havemos de guerrear ali outros tantos anos,",
        "e no décimo tomaremos a cidade de largas ruas.’",
        "Assim falou ele; e tudo isso está agora a cumprir-se.”"
      ],
      notas: [
        { termo: "Áulis", texto: "Porto da Grécia onde a frota se reuniu antes de partir para Troia." }
      ]
    },
    {
      titulo: "Nestor: fiquemos",
      versos: "333–356",
      linhas: [
        "Assim falou; e os argivos gritaram bem alto,",
        "e as naves retumbaram terrivelmente com o clamor dos aqueus,",
        "que louvavam a palavra do divino Odisseu.",
        "Então lhes falou Nestor, o cavaleiro de Gerena:",
        "“Ora vejam! Estais em assembleia como meninos pequenos,",
        "que não se importam nada com trabalhos de guerra.",
        "Onde vão parar os nossos pactos e juramentos?",
        "Que se lancem então ao fogo os conselhos e os planos dos homens,",
        "as libações puras e os apertos de mão em que confiamos!",
        "Brigamos com palavras à toa, e não achamos remédio nenhum,",
        "embora estejamos aqui há tanto tempo.",
        "Atrida, mantém tu, como antes, a tua decisão firme,",
        "e conduz os argivos pelos combates duros;",
        "e que pereçam esses um ou dois que, à parte dos aqueus,",
        "fazem planos por conta própria — nada hão de conseguir —",
        "de voltar a Argos antes de saber",
        "se a promessa de Zeus porta-égide é falsa ou não.",
        "Pois eu digo que o poderoso filho de Crono acenou com a cabeça",
        "naquele dia em que os argivos embarcaram nas naves velozes,",
        "levando morte e destino aos troianos:",
        "relampejou à direita{1} e mostrou sinais de bom agouro.",
        "Portanto ninguém tenha pressa de voltar para casa",
        "antes de cada um se deitar com a mulher de um troiano",
        "e vingar as lutas e os gemidos de Helena.”"
      ],
      notas: [
        { termo: "relampejou à direita", texto: "Nos presságios gregos o lado direito é de bom agouro; o esquerdo, de mau." }
      ]
    },
    {
      titulo: "Por tribos e por clãs",
      versos: "357–393",
      linhas: [
        "“Mas se alguém tiver muita vontade de voltar para casa,",
        "que ponha a mão na sua nave negra de bons bancos,",
        "para que antes dos outros encontre a morte e o destino.",
        "Mas tu, ó rei, decide bem, e ouve também outro:",
        "não é de deitar fora a palavra que te vou dizer.",
        "Separa os homens por tribos e por clãs{1}, Agamêmnon,",
        "para que clã socorra clã, e tribo socorra tribo.",
        "Se fizeres assim, e os aqueus te obedecerem,",
        "saberás qual dos chefes é covarde, e qual dos soldados,",
        "e qual é valente, pois cada um combaterá entre os seus.",
        "E saberás se é por vontade divina que não tomas a cidade,",
        "ou pela covardia dos homens e pela sua inépcia na guerra.”",
        "Respondendo-lhe, disse o soberano Agamêmnon:",
        "“Mais uma vez, ancião, vences na assembleia os filhos dos aqueus.",
        "Quem dera, Zeus pai, Atena e Apolo,",
        "que eu tivesse dez conselheiros assim entre os aqueus:",
        "depressa cairia a cidade do soberano Príamo,",
        "tomada e arrasada pelas nossas mãos.",
        "Mas o Cronida, Zeus porta-égide, deu-me desgraças:",
        "lançou-me em brigas e contendas inúteis.",
        "Pois eu e Aquiles combatemos por causa de uma moça,",
        "com palavras contrárias, e fui eu quem começou a irar-se.",
        "Se um dia voltarmos a pensar como um só homem,",
        "então nem por um instante será adiada a ruína dos troianos.",
        "Agora ide comer, para depois travarmos combate.",
        "Cada um afie bem a lança e prepare bem o escudo,",
        "cada um dê de comer aos cavalos de pés velozes,",
        "e cada um repare bem o carro, pensando na batalha,",
        "para que o dia inteiro nos meçamos no combate terrível.”"
      ],
      notas: [
        { termo: "por tribos e por clãs", texto: "Organizar o exército pelos laços de parentesco e de origem, de modo que cada homem combata ao lado dos seus." }
      ]
    },
    {
      titulo: "O sacrifício de Agamêmnon",
      versos: "394–420",
      linhas: [
        "Assim falou; e os argivos gritaram bem alto,",
        "como a onda contra uma falésia alta,",
        "quando o vento sul a empurra contra um promontório saliente",
        "que as ondas nunca deixam, venham elas de onde vierem.",
        "Levantaram-se e dispersaram-se pelas naves;",
        "acenderam fogo nas tendas e tomaram a refeição.",
        "Cada um sacrificava a um dos deuses que existem para sempre,",
        "rogando escapar da morte e do trabalho da guerra.",
        "E Agamêmnon, soberano de homens, sacrificou ao filho de Crono",
        "um touro gordo de cinco anos,",
        "e chamou os anciãos, os primeiros de todos os aqueus:",
        "antes de todos Nestor, e depois o soberano Idomeneu;",
        "em seguida os dois Ájax e o filho de Tideu{1};",
        "e em sexto lugar Odisseu, igual a Zeus no conselho.",
        "Menelau, de forte grito de guerra, veio por si mesmo,",
        "pois sabia no coração como o irmão andava atarefado.",
        "Puseram-se em volta do touro e tomaram os grãos de cevada;",
        "e, entre eles, orou o soberano Agamêmnon:",
        "“Zeus gloriosíssimo, grandíssimo, senhor das nuvens escuras,",
        "que habitas o céu: que o sol não se ponha nem venha a escuridão",
        "antes que eu derrube de alto a baixo o palácio de Príamo,",
        "enegrecido de fumo, e queime as suas portas com fogo devorador,",
        "e rasgue no peito de Heitor a túnica, aberta pelo bronze;",
        "e que muitos companheiros dele caiam de cara na poeira,",
        "em volta, e mordam a terra.”"
      ],
      notas: [
        { termo: "o filho de Tideu", texto: "Diomedes, rei de Argos e um dos melhores guerreiros gregos." }
      ]
    },
    {
      titulo: "A refeição e a ordem de marcha",
      versos: "421–444",
      linhas: [
        "Assim falou; mas o filho de Crono ainda não lhe deu cumprimento:",
        "aceitou os sacrifícios e aumentou-lhe o trabalho indesejado.",
        "Depois de orarem e de espalharem os grãos,",
        "puxaram para trás a cabeça da vítima, degolaram-na e esfolaram-na;",
        "cortaram as coxas, cobriram-nas com uma dupla camada de gordura",
        "e sobre elas puseram pedaços de carne crua.",
        "Queimaram tudo sobre lenha rachada e sem folhas,",
        "e seguravam as vísceras espetadas sobre a chama.",
        "Queimadas as coxas e provadas as vísceras,",
        "cortaram o resto em pedaços, espetaram-nos,",
        "assaram-nos com cuidado e retiraram tudo do fogo.",
        "E, terminado o trabalho, prepararam o banquete;",
        "e comeram, sem que a ninguém faltasse a sua parte igual.",
        "Quando afastaram o desejo de comer e de beber,",
        "começou a falar Nestor, o cavaleiro de Gerena:",
        "“Gloriosíssimo Atrida, Agamêmnon, soberano de homens:",
        "não fiquemos mais aqui a conversar, nem adiemos por muito tempo",
        "a obra que o deus agora nos põe nas mãos.",
        "Vamos: que os arautos dos aqueus vestidos de bronze",
        "façam o anúncio e juntem o exército junto às naves;",
        "e nós, assim reunidos, percorramos o vasto acampamento,",
        "para acordarmos mais depressa a guerra aguda.”",
        "Assim falou; e Agamêmnon, soberano de homens, não desobedeceu."
      ]
    },
    {
      titulo: "A égide de Atena",
      versos: "445–458",
      linhas: [
        "Logo mandou que os arautos de voz clara",
        "convocassem para o combate os aqueus de longos cabelos.",
        "Fizeram o anúncio, e os homens juntaram-se muito depressa.",
        "Os reis criados por Zeus, em volta do Atrida,",
        "corriam de um lado para o outro, pondo-os em ordem;",
        "e no meio deles ia Atena de olhos brilhantes,",
        "segurando a égide preciosa, que não envelhece nem morre,",
        "da qual pendem cem franjas de ouro, todas bem trançadas,",
        "e cada uma vale cem bois.",
        "Com ela, resplandecente, atravessou o exército dos aqueus,",
        "incitando-os a avançar; e em cada peito despertou força",
        "para guerrear e combater sem descanso.",
        "E logo a guerra lhes ficou mais doce do que voltar,",
        "nas naves recurvas, para a terra amada dos pais."
      ]
    },
    {
      titulo: "Como aves, como moscas",
      versos: "459–483",
      linhas: [
        "Como as muitas tribos de aves aladas —",
        "gansos, grous, ou cisnes de pescoço comprido —",
        "voam de um lado para o outro no prado da Ásia,",
        "junto às correntes do Caístro, gloriando-se nas asas,",
        "e vão pousando com gritos, e o prado ressoa:",
        "assim as muitas tribos de homens saíam das naves e das tendas",
        "para a planície do Escamandro; e a terra retumbava terrivelmente",
        "sob os pés dos homens e dos cavalos.",
        "Pararam no prado florido do Escamandro,",
        "incontáveis como as folhas e as flores na sua estação.",
        "Como as muitas tribos de moscas espessas",
        "que andam em volta do curral do pastor, na primavera,",
        "quando o leite molha os baldes:",
        "tantos eram os aqueus de longos cabelos parados na planície,",
        "diante dos troianos, querendo despedaçá-los.",
        "E como os cabreiros separam facilmente os rebanhos largos de cabras,",
        "quando elas se misturam no pasto,",
        "assim os chefes os punham em ordem de um lado e de outro,",
        "para entrarem no combate; e entre eles ia o soberano Agamêmnon,",
        "nos olhos e na cabeça semelhante a Zeus que se alegra com o raio,",
        "na cintura a Ares, no peito a Posídon.",
        "Como o touro que na manada se distingue de todos,",
        "pois é o que salta à vista entre as vacas reunidas:",
        "assim fez Zeus, naquele dia, o filho de Atreu —",
        "notável entre muitos, e o primeiro entre os heróis."
      ]
    },
    {
      titulo: "Nova invocação às Musas",
      versos: "484–493",
      linhas: [
        "Dizei-me agora, Musas que habitais o Olimpo —",
        "pois vós sois deusas, estais presentes e sabeis tudo,",
        "ao passo que nós só ouvimos falar e nada sabemos —,",
        "quem foram os chefes e os senhores dos dânaos.",
        "À multidão eu não poderia contar nem nomear,",
        "nem que tivesse dez línguas e dez bocas,",
        "voz que não se quebrasse e um coração de bronze dentro do peito,",
        "a não ser que as Musas do Olimpo, filhas de Zeus porta-égide,",
        "me trouxessem à memória todos os que vieram a Ílion.",
        "Direi, então, os capitães das naves e todas as naves."
      ]
    },
    {
      titulo: "Resumo: o Catálogo das Naves",
      versos: "494–759",
      tipo: "resumo",
      paragrafos: [
        "Segue-se o Catálogo das Naves: a enumeração de todos os contingentes gregos, região por região, com os nomes dos capitães, as cidades de onde vieram e o número de navios de cada um. São vinte e nove contingentes e mil cento e oitenta e seis naves ao todo, começando pelos beócios e passando por Atenas, Micenas, Esparta, Pilos, Argos, Creta, Ítaca, Rodes e as ilhas.",
        "São quase trezentos versos de nomes próprios, quase sem ação. Duas coisas valem a pena saber sobre eles. A geografia que descrevem é muito anterior ao poema: inclui cidades que já estavam abandonadas no tempo de Homero, e arqueólogos a usaram como mapa da Grécia micênica. E, recitado em voz alta diante de um público reunido, o catálogo funcionava como uma lista de honra, em que cada ouvinte podia esperar o nome da sua própria terra.",
        "No meio da lista aparecem os mirmidões de Aquiles, com cinquenta naves — e o poeta interrompe a enumeração para lembrar que eles não estão combatendo, porque o chefe continua parado junto aos navios."
      ]
    },
    {
      titulo: "Os melhores, e a marcha",
      versos: "760–785",
      linhas: [
        "Estes eram os chefes e os senhores dos dânaos.",
        "Quem era, então, o melhor de todos? Dize-mo, Musa —",
        "o melhor dos homens e dos cavalos que seguiram os Atridas.",
        "Dos cavalos, os melhores eram as éguas de Eumelo,",
        "velozes como aves, iguais no pelo e na idade,",
        "e com o dorso nivelado como por um cordel.",
        "Apolo do arco de prata criara-as na Piéria, as duas éguas,",
        "e elas levavam consigo o pânico da guerra.",
        "Dos homens, o melhor de longe era Ájax, filho de Télamon,",
        "enquanto Aquiles esteve irado — pois este era muito mais forte,",
        "e mais fortes eram também os cavalos que levavam o filho de Peleu.",
        "Mas ele estava deitado junto às naves recurvas,",
        "alimentando a ira contra Agamêmnon, pastor de povos;",
        "e a gente dele, na praia, divertia-se",
        "com o disco, o dardo e o arco.",
        "Os cavalos estavam parados, cada um junto ao seu carro,",
        "comendo loto e aipo do brejo;",
        "e os carros estavam bem cobertos nas tendas dos seus donos.",
        "E os homens, com saudade do chefe amigo da guerra,",
        "andavam de um lado para o outro pelo acampamento, e não combatiam.",
        "Os outros marchavam como se toda a terra ardesse em fogo;",
        "e o chão gemia por baixo, como quando Zeus, que se alegra com o raio,",
        "açoita a terra em volta de Tifeu{1}, no país dos árimos.",
        "Assim gemia muito a terra sob os pés dos que marchavam;",
        "e muito depressa atravessaram a planície."
      ],
      notas: [
        { termo: "Tifeu", texto: "Monstro que se revoltou contra Zeus e foi fulminado por ele; a tradição punha-o enterrado debaixo de um vulcão." }
      ]
    },
    {
      titulo: "Íris entre os troianos",
      versos: "786–815",
      linhas: [
        "Aos troianos veio, como mensageira de Zeus porta-égide,",
        "Íris de pés velozes, com notícias pesadas.",
        "Eles estavam em assembleia às portas de Príamo,",
        "todos reunidos, os moços e os velhos.",
        "Pondo-se ao lado deles, falou Íris de pés velozes,",
        "tomando a voz de Polites, filho de Príamo,",
        "que costumava ficar de sentinela dos troianos,",
        "confiado na rapidez dos pés,",
        "no alto do túmulo do velho Esietes,",
        "à espera de que os aqueus saíssem das naves.",
        "Com essa aparência, disse Íris de pés velozes:",
        "“Ancião, sempre te foram caras as palavras sem medida,",
        "como no tempo da paz; mas levantou-se agora uma guerra sem trégua.",
        "Já entrei muitas vezes em batalhas de homens,",
        "mas nunca vi um exército assim, tão grande:",
        "são como as folhas, ou como os grãos de areia,",
        "e vêm pela planície para combater junto à cidade.",
        "Heitor, a ti sobretudo eu dou esta ordem; faze assim:",
        "como há muitos aliados espalhados pela grande cidade de Príamo,",
        "e cada povo tem a sua língua{1},",
        "que cada chefe dê a palavra aos que comanda",
        "e os leve para fora, pondo em ordem os seus conterrâneos.”",
        "Assim falou; e Heitor bem reconheceu a palavra da deusa.",
        "Logo desfez a assembleia, e correram todos às armas.",
        "Abriram-se todas as portas, e o exército saiu,",
        "a pé e a cavalo; e levantou-se um grande estrondo.",
        "Há diante da cidade um outeiro íngreme, isolado na planície,",
        "com caminho livre de um lado e do outro.",
        "Os homens chamam-lhe Batieia, e os imortais",
        "chamam-lhe o túmulo de Mirine.",
        "Ali se puseram em ordem os troianos e os seus aliados."
      ],
      notas: [
        { termo: "cada povo tem a sua língua", texto: "Os troianos comandam uma coalizão de povos da Ásia Menor que não falam a mesma língua entre si; o exército grego, ao contrário, é de língua única." }
      ]
    },
    {
      titulo: "Resumo: o catálogo dos troianos",
      versos: "816–877",
      tipo: "resumo",
      paragrafos: [
        "Fecha o canto o catálogo dos troianos e dos seus aliados, bem mais curto: dezesseis contingentes, e sem contagem de navios, porque combatem em casa. Heitor comanda os troianos; ao lado deles vêm os dárdanos de Eneias, os lícios de Sarpédon e Glauco, e ainda cários, frígios, meónios, trácios, páflagones e outros povos da Ásia Menor e dos Bálcãs — a coalizão de línguas diferentes que Íris acabou de mencionar.",
        "Vários dos nomes citados aqui só voltam a aparecer no poema no momento em que morrem."
      ]
    }
  ]
});
