/* Ilíada — Canto III
   Tradução em versos livres. */

window.ILIADA.cantos.push({
  numero: 3,
  romano: "III",
  titulo: "O duelo por Helena",
  estrofes: [
    {
      titulo: "Os dois exércitos",
      versos: "1–14",
      linhas: [
        "Depois que uns e outros se ordenaram, cada qual com seus chefes,",
        "avançaram os troianos com clamor e grito, como aves:",
        "assim é o clamor dos grous debaixo do céu,",
        "quando fogem do inverno e da chuva sem fim",
        "e voam com gritos para as correntes do Oceano,",
        "levando morte e destino aos homens pigmeus{1},",
        "e ao amanhecer lhes trazem a discórdia funesta.",
        "Mas os aqueus avançavam em silêncio, respirando fúria,",
        "decididos no coração a defender-se uns aos outros.",
        "Como o vento sul espalha névoa pelos cumes de um monte —",
        "péssima para os pastores, e para o ladrão melhor que a noite,",
        "pois só se enxerga até onde se atira uma pedra —,",
        "assim, sob os pés dos que marchavam, subia a poeira espessa;",
        "e muito depressa atravessaram a planície."
      ],
      notas: [
        { termo: "os homens pigmeus", texto: "A lenda de uma guerra anual entre os grous e um povo minúsculo, que os gregos situavam no extremo sul, para além do Egito." }
      ]
    },
    {
      titulo: "Páris recua",
      versos: "15–37",
      linhas: [
        "Quando já estavam perto, avançando uns contra os outros,",
        "saiu à frente dos troianos Alexandre{1} semelhante a um deus,",
        "com uma pele de leopardo sobre os ombros, o arco recurvo",
        "e a espada; e, brandindo duas lanças de ponta de bronze,",
        "desafiava os melhores dos argivos",
        "a medir-se com ele em combate terrível, frente a frente.",
        "Assim que o viu Menelau, caro a Ares,",
        "vindo à frente da multidão a passos largos,",
        "alegrou-se como o leão que encontra uma presa grande —",
        "um veado de chifres ou uma cabra selvagem — estando faminto,",
        "e a devora sofregamente, ainda que sobre ele avancem",
        "cães velozes e rapazes robustos:",
        "assim se alegrou Menelau ao ver com os próprios olhos",
        "Alexandre semelhante a um deus, pois julgou vingar-se do culpado.",
        "E logo saltou do carro para o chão, com as armas.",
        "Mas quando Alexandre, semelhante a um deus, o viu aparecer",
        "entre os campeões, faltou-lhe o coração,",
        "e recuou para o meio dos companheiros, fugindo à morte.",
        "Como quem, numa garganta de montanha, dá com uma serpente",
        "e salta para trás, e o tremor lhe toma os membros,",
        "e recua, e a palidez lhe cobre o rosto:",
        "assim mergulhou de novo na turba dos troianos altivos",
        "Alexandre semelhante a um deus, com medo do filho de Atreu."
      ],
      notas: [
        { termo: "Alexandre", texto: "O outro nome de Páris, o príncipe troiano que levou Helena." }
      ]
    },
    {
      titulo: "A repreensão de Heitor",
      versos: "38–57",
      linhas: [
        "Vendo isso, Heitor{1} repreendeu-o com palavras humilhantes:",
        "“Páris funesto, belíssimo de aparência, louco por mulheres, enganador!",
        "Quem dera não tivesses nascido, ou tivesses morrido solteiro.",
        "Isso eu preferiria, e seria muito melhor",
        "do que seres assim uma vergonha, um homem que os outros olham de lado.",
        "Bem devem rir de nós os aqueus de longos cabelos,",
        "julgando que temos por campeão um homem de bela figura,",
        "mas sem força no peito e sem coragem nenhuma.",
        "Eras assim quando, em naves marinhas,",
        "navegaste o mar, juntando companheiros de confiança,",
        "e te misturaste com estrangeiros, e trouxeste de terra distante",
        "uma mulher formosa, nora de homens de lança —",
        "grande desgraça para teu pai, para a cidade e para todo o povo,",
        "alegria para os inimigos e vergonha para ti próprio?",
        "E agora não esperas Menelau, caro a Ares?",
        "Saberias então de que homem tens a esposa florescente.",
        "De nada te valeriam a cítara e os dons de Afrodite,",
        "nem a cabeleira nem a beleza, quando rolasses na poeira.",
        "Mas os troianos são muito covardes: senão, já há muito tempo",
        "vestirias uma túnica de pedra pelo mal que fizeste.”"
      ],
      notas: [
        { termo: "Heitor", texto: "O irmão mais velho de Páris, o maior guerreiro de Troia e o homem em quem a cidade se apoia." }
      ]
    },
    {
      titulo: "A proposta de Páris",
      versos: "58–75",
      linhas: [
        "Respondeu-lhe então Alexandre semelhante a um deus:",
        "“Heitor, repreendes-me com razão, e não além da medida.",
        "O teu coração é sempre incansável, como o machado",
        "que atravessa a madeira na mão do homem que talha.",
        "Mas não me atires à cara os dons amáveis da dourada Afrodite:",
        "não são de recusar os dons gloriosos dos deuses,",
        "que eles próprios dão, e que ninguém escolheria por si mesmo.",
        "Agora, se queres que eu combata e lute,",
        "faze sentar os outros troianos e todos os aqueus,",
        "e ponde-me no meio, com Menelau caro a Ares,",
        "a combater por Helena e por todos os bens dela.",
        "Aquele de nós que vencer e se mostrar mais forte,",
        "que leve para casa os bens e a mulher;",
        "e vós, os demais, jurai amizade com sacrifícios.”"
      ]
    },
    {
      titulo: "As armas no chão",
      versos: "76–85",
      linhas: [
        "Assim falou; e Heitor alegrou-se muito ao ouvi-lo.",
        "Foi para o meio e, segurando a lança pela haste,",
        "conteve as falanges troianas; e todas se sentaram.",
        "Mas os aqueus de longos cabelos atiravam nele,",
        "apontando-lhe flechas e pedras.",
        "Então gritou bem alto o soberano de homens, Agamêmnon:",
        "“Parai, argivos! Não atireis, jovens dos aqueus!",
        "Heitor do elmo faiscante quer dizer alguma coisa.”",
        "Assim falou; e eles cessaram o combate e calaram-se depressa.",
        "E Heitor, entre os dois exércitos, disse:"
      ]
    },
    {
      titulo: "O pacto",
      versos: "86–120",
      linhas: [
        "“Ouvi de mim, troianos e aqueus de belas grevas,",
        "a palavra de Alexandre, por causa de quem nasceu esta contenda.",
        "Manda ele que os troianos e todos os aqueus",
        "deponham no chão fecundo as belas armas,",
        "e que ele próprio, no meio, com Menelau caro a Ares,",
        "combata sozinho por Helena e por todos os bens dela.",
        "Aquele que vencer e se mostrar mais forte,",
        "que leve para casa os bens e a mulher;",
        "e os demais jurem amizade com sacrifícios.”",
        "Assim falou; e todos ficaram em silêncio, calados.",
        "Então lhes falou Menelau, o de forte grito de guerra:",
        "“Ouvi-me também a mim: a dor chegou sobretudo ao meu coração.",
        "Penso que argivos e troianos já se devem separar,",
        "pois muito sofrestes por causa da minha contenda,",
        "que Alexandre começou.",
        "Àquele de nós dois a quem estiverem preparadas a morte e a sorte,",
        "que morra; e os demais separem-se depressa.",
        "Trazei dois cordeiros: um branco e uma ovelha negra,",
        "para a Terra e para o Sol; e nós traremos outro para Zeus.",
        "E trazei aqui a força de Príamo, para que ele próprio jure,",
        "pois os filhos dele são arrogantes e sem palavra —",
        "que ninguém, por soberba, viole os juramentos de Zeus.",
        "O espírito dos moços anda sempre a esvoaçar;",
        "mas naquilo em que um velho toma parte,",
        "ele olha ao mesmo tempo para a frente e para trás,",
        "para que a coisa saia melhor para os dois lados.”",
        "Assim falou; e alegraram-se aqueus e troianos,",
        "esperando descansar da guerra dolorosa.",
        "Detiveram os cavalos nas fileiras, desceram dos carros,",
        "tiraram as armas e puseram-nas no chão,",
        "muito perto umas das outras — pouca terra ficava no meio.",
        "Heitor mandou à cidade dois arautos, depressa,",
        "para trazerem os cordeiros e chamarem Príamo.",
        "E o soberano Agamêmnon mandou Taltíbio",
        "ir às naves recurvas buscar outro cordeiro; e ele não desobedeceu."
      ]
    },
    {
      titulo: "Íris e o tecido de Helena",
      versos: "121–145",
      linhas: [
        "Entretanto Íris{1} foi como mensageira a Helena de alvos braços,",
        "tomando a figura da cunhada, mulher de Helicáon:",
        "Laódice, a mais bela das filhas de Príamo.",
        "Encontrou-a no palácio, tecendo uma grande tela dupla,",
        "de púrpura, na qual ia bordando os muitos combates",
        "dos troianos domadores de cavalos e dos aqueus vestidos de bronze —",
        "combates que por causa dela suportavam sob as mãos de Ares.",
        "Pôs-se a seu lado Íris de pés velozes, e disse:",
        "“Vem cá, querida, para veres o espanto que fazem",
        "os troianos domadores de cavalos e os aqueus vestidos de bronze.",
        "Eles, que antes moviam uns contra os outros a guerra chorosa,",
        "agora estão sentados em silêncio — a batalha cessou —,",
        "encostados aos escudos, e ao lado as longas lanças fincadas.",
        "Mas Alexandre e Menelau, caro a Ares,",
        "vão combater por ti com as longas lanças;",
        "e do vencedor serás chamada a esposa querida.”",
        "Assim falando, a deusa lançou-lhe no coração um doce desejo",
        "do marido de antes, da cidade e dos pais.",
        "Logo se cobriu com um véu de linho brilhante",
        "e saiu do quarto, deixando cair uma lágrima redonda —",
        "não sozinha: seguiam-na duas servas,",
        "Etra, filha de Piteu, e Clímene de olhos de novilha.",
        "Depressa chegaram ao lugar onde estão as portas Ceias."
      ],
      notas: [
        { termo: "Íris", texto: "A mensageira dos deuses, a que desce pelo arco-íris. Como os arautos entre os homens, leva recados e não responde por eles." }
      ]
    },
    {
      titulo: "Os anciãos na muralha",
      versos: "146–165",
      linhas: [
        "Ali estavam, em torno de Príamo, Pântoo e Timetes,",
        "Lampo, Clítio e Hicetáon, rebento de Ares,",
        "e Ucalegonte e Antenor, ambos prudentes:",
        "os anciãos do povo, sentados junto às portas Ceias.",
        "A velhice já os afastara da guerra, mas eram bons oradores,",
        "semelhantes às cigarras que, no bosque, pousadas numa árvore,",
        "soltam a sua voz delicada.",
        "Assim estavam sentados na torre os chefes dos troianos.",
        "Quando viram Helena aproximar-se da muralha,",
        "disseram baixinho, uns aos outros, palavras aladas:",
        "“Não é de espantar que troianos e aqueus de belas grevas",
        "venham sofrendo há tanto tempo por uma mulher assim:",
        "é terrivelmente parecida, de rosto, com as deusas imortais.",
        "Mas, ainda sendo o que é, que parta nas naves",
        "e não fique aqui como ruína para nós e para os nossos filhos.”",
        "Assim falavam. Mas Príamo chamou Helena em voz alta:",
        "“Vem cá, filha querida, senta-te diante de mim,",
        "para veres o teu marido de antes, os teus parentes e os teus amigos.",
        "Tu não és culpada a meus olhos: culpados são os deuses,",
        "que levantaram contra mim a guerra chorosa dos aqueus.”"
      ]
    },
    {
      titulo: "Helena responde",
      versos: "166–180",
      linhas: [
        "“Dize-me também o nome daquele homem enorme:",
        "quem é aquele guerreiro aqueu, nobre e alto?",
        "Outros há que lhe passam a cabeça em altura,",
        "mas nunca vi com os meus olhos um homem tão belo",
        "nem tão imponente: parece um rei.”",
        "Respondeu-lhe Helena, mulher divina entre as mulheres:",
        "“Tu me és venerando, sogro querido, e temível.",
        "Quem dera me tivesse agradado a morte cruel",
        "quando vim para cá com o teu filho, deixando o meu leito,",
        "os meus parentes, a minha filha já crescida",
        "e as companheiras queridas da minha idade.",
        "Mas não foi assim que aconteceu; e por isso me consumo em lágrimas.",
        "Vou dizer-te o que me perguntas:",
        "esse é o Atrida, Agamêmnon de amplo domínio,",
        "ao mesmo tempo bom rei e forte lanceiro.",
        "Foi meu cunhado — cadela que sou —, se é que isso alguma vez existiu.”"
      ]
    },
    {
      titulo: "O reconhecimento",
      versos: "181–202",
      linhas: [
        "Assim falou; e o ancião, admirado, disse:",
        "“Feliz Atrida, filho de boa sorte, abençoado pelos deuses!",
        "Quantos filhos dos aqueus te estão sujeitos!",
        "Já uma vez fui à Frígia{1} de muitas vinhas,",
        "e vi ali muitos frígios de cavalos velozes,",
        "os povos de Otreu e de Mígdon semelhante a um deus,",
        "acampados então às margens do rio Sangário.",
        "Eu estava entre eles como aliado, contado no exército,",
        "naquele dia em que chegaram as Amazonas{2}, iguais aos homens.",
        "Mas nem aqueles eram tantos como os aqueus de olhos vivos.”",
        "E, vendo Odisseu, o ancião perguntou de novo:",
        "“Dize-me também deste, filha querida: quem é?",
        "É mais baixo do que o Atrida Agamêmnon por uma cabeça,",
        "mas parece mais largo de ombros e de peito.",
        "As armas dele estão pousadas no chão fecundo,",
        "e ele próprio percorre as fileiras dos homens como um carneiro:",
        "pareço vê-lo como um carneiro de espesso velo",
        "atravessando um grande rebanho de ovelhas brancas.”"
      ],
      notas: [
        { termo: "à Frígia", texto: "Região do interior da Ásia Menor." },
        { termo: "as Amazonas", texto: "O povo de mulheres guerreiras." }
      ]
    },
    {
      titulo: "Antenor recorda a embaixada",
      versos: "203–224",
      linhas: [
        "Respondendo-lhe, disse Antenor, o de bom conselho:",
        "“Senhora, na verdade falaste com acerto.",
        "Já uma vez veio aqui o divino Odisseu,",
        "numa embaixada{1} por tua causa, com Menelau caro a Ares.",
        "Eu próprio os recebi e hospedei no meu palácio,",
        "e conheci de perto a figura e o modo de pensar dos dois.",
        "Quando estavam de pé no meio dos troianos reunidos,",
        "Menelau passava-lhe os ombros largos por cima;",
        "mas, sentados os dois, Odisseu era o mais imponente.",
        "E quando teciam diante de todos as palavras e os conselhos,",
        "Menelau falava corrido, poucas palavras e muito claras,",
        "pois não era homem de falar muito nem de sair do assunto —",
        "e olhe que era o mais novo dos dois.",
        "Mas quando se levantava Odisseu de muitos conselhos,",
        "ficava parado, de olhos baixos, cravados no chão,",
        "e não movia o cetro nem para a frente nem para trás:",
        "segurava-o teso, como um homem sem prática.",
        "Qualquer um o tomaria por um sujeito emburrado, e ainda por tolo.",
        "Mas quando soltava do peito a grande voz,",
        "e as palavras vinham como flocos de neve no inverno,",
        "então nenhum outro mortal se media com Odisseu;",
        "e já não estranhávamos a figura dele.”"
      ],
      notas: [
        { termo: "numa embaixada", texto: "Antes da guerra, Menelau e Odisseu vieram a Troia pedir a devolução de Helena, e os troianos recusaram." }
      ]
    },
    {
      titulo: "Os irmãos que faltam",
      versos: "225–244",
      linhas: [
        "Em terceiro lugar, vendo Ájax, perguntou o ancião:",
        "“E quem é aquele outro aqueu, nobre e alto,",
        "que passa os argivos pela cabeça e pelos ombros largos?”",
        "Respondeu-lhe Helena de longo vestido, divina entre as mulheres:",
        "“Esse é o enorme Ájax, a muralha dos aqueus.",
        "E do outro lado está Idomeneu, semelhante a um deus entre os cretenses,",
        "e em volta dele estão reunidos os chefes de Creta.",
        "Muitas vezes Menelau, caro a Ares, o hospedou em nossa casa,",
        "quando ele vinha de Creta.",
        "E agora vejo todos os outros aqueus de olhos vivos,",
        "que eu bem saberia reconhecer e nomear;",
        "mas há dois chefes do exército que não consigo ver:",
        "Castor, domador de cavalos, e Polideuces{1}, bom no pugilato,",
        "meus irmãos, que a mesma mãe deu à luz comigo.",
        "Ou não vieram da amável Lacedemônia{2},",
        "ou vieram até aqui nas naves marinhas,",
        "mas agora não querem entrar no combate dos homens,",
        "com medo da vergonha e das muitas afrontas que são minhas.”",
        "Assim falou; mas a eles já a terra que dá a vida",
        "os retinha lá, na Lacedemônia, na terra amada dos pais."
      ],
      notas: [
        { termo: "Castor e Polideuces", texto: "Os irmãos gêmeos de Helena, cultuados mais tarde como os Dióscuros. Polideuces é o mesmo que Pólux." },
        { termo: "Lacedemônia", texto: "Esparta, o reino de Menelau, de onde Helena partiu." }
      ]
    },
    {
      titulo: "Os cordeiros do juramento",
      versos: "245–258",
      linhas: [
        "Entretanto, pela cidade, os arautos levavam",
        "as ofertas para os juramentos fiéis diante dos deuses:",
        "dois cordeiros e o vinho que alegra, fruto da terra,",
        "num odre de pele de cabra; e o arauto Ídeo",
        "levava uma cratera brilhante e taças de ouro.",
        "Chegou-se ao ancião e disse-lhe, para o despertar:",
        "“Levanta-te, filho de Laomedonte{1}! Chamam-te os primeiros",
        "dos troianos domadores de cavalos e dos aqueus vestidos de bronze,",
        "para que desças à planície e jures os juramentos fiéis.",
        "Alexandre e Menelau, caro a Ares, hão de combater",
        "com as longas lanças pela mulher;",
        "e a mulher e os bens seguirão o vencedor.",
        "E nós, os demais, tendo jurado amizade,",
        "habitaremos Troia de fundo solo, e eles voltarão",
        "para Argos criadora de cavalos e para a Acaia de belas mulheres.”"
      ],
      notas: [
        { termo: "filho de Laomedonte", texto: "Laomedonte, pai de Príamo, foi o rei em cujo tempo se ergueram as muralhas de Troia." }
      ]
    },
    {
      titulo: "Príamo desce à planície",
      versos: "259–275",
      linhas: [
        "Assim falou; e o ancião estremeceu, mas mandou aos companheiros",
        "que atrelassem os cavalos; e eles obedeceram depressa.",
        "Príamo subiu ao carro e puxou as rédeas para trás;",
        "ao lado dele subiu Antenor, no belo carro.",
        "Os dois conduziram os cavalos velozes pelas portas Ceias, para a planície.",
        "Quando chegaram junto dos troianos e dos aqueus,",
        "desceram do carro para o chão fecundo",
        "e foram para o meio dos troianos e dos aqueus.",
        "Logo se ergueu Agamêmnon, soberano de homens,",
        "e ergueu-se também Odisseu de muitos conselhos.",
        "Os arautos ilustres juntaram as ofertas",
        "para os juramentos fiéis diante dos deuses,",
        "misturaram o vinho na cratera",
        "e derramaram água sobre as mãos dos reis.",
        "O Atrida puxou com as mãos a faca que sempre trazia",
        "junto à grande bainha da espada,",
        "e cortou pelos das cabeças dos cordeiros{1};",
        "e os arautos repartiram-nos entre os primeiros",
        "dos troianos e dos aqueus."
      ],
      notas: [
        { termo: "cortou pelos das cabeças dos cordeiros", texto: "No rito do juramento cortavam-se pelos da vítima e repartiam-se entre os presentes, que ficavam assim ligados ao pacto." }
      ]
    },
    {
      titulo: "O juramento",
      versos: "276–301",
      linhas: [
        "Entre eles, o Atrida orou em voz alta, com as mãos erguidas:",
        "“Zeus pai, que governas do Ida{1}, gloriosíssimo, grandíssimo;",
        "e tu, Sol, que tudo vês e tudo ouves;",
        "e vós, Rios e Terra, e vós que lá em baixo castigais",
        "os homens já mortos que juraram falso{2}:",
        "sede testemunhas e guardai os juramentos fiéis.",
        "Se Alexandre matar Menelau,",
        "que fique com Helena e com todos os bens,",
        "e nós voltaremos nas naves marinhas.",
        "Mas se Menelau de louros cabelos matar Alexandre,",
        "então que os troianos devolvam Helena e todos os bens,",
        "e paguem aos argivos a reparação que for justa,",
        "de modo que fique lembrada entre os homens que vierem depois.",
        "E se Príamo e os filhos de Príamo não quiserem pagar-me",
        "a reparação, caído que seja Alexandre,",
        "então continuarei a combater por causa desse pagamento,",
        "ficando aqui até encontrar um fim para a guerra.”",
        "Disse, e cortou a garganta dos cordeiros com o bronze impiedoso;",
        "e pô-los no chão, arquejando, sem fôlego,",
        "pois o bronze lhes tirara a força.",
        "Tirando vinho da cratera com as taças, derramavam-no",
        "e rogavam aos deuses que existem para sempre.",
        "E assim dizia um, entre aqueus e troianos:",
        "“Zeus gloriosíssimo, grandíssimo, e vós, outros deuses imortais:",
        "o lado que primeiro fizer o mal contra estes juramentos,",
        "que os miolos lhes corram pelo chão como este vinho —",
        "os deles e os dos seus filhos —,",
        "e que as mulheres deles sejam dominadas por outros.”"
      ],
      notas: [
        { termo: "que governas do Ida", texto: "Monte perto de Troia, de onde Zeus acompanha a guerra." },
        { termo: "os homens já mortos que juraram falso", texto: "As potências do mundo subterrâneo que castigam o perjúrio: quem jurava falso pagava depois de morto." }
      ]
    },
    {
      titulo: "As sortes no elmo",
      versos: "302–323",
      linhas: [
        "Assim diziam; mas o filho de Crono ainda não lhes deu cumprimento.",
        "E entre eles falou Príamo, da linhagem de Dárdano:",
        "“Ouvi-me, troianos e aqueus de belas grevas:",
        "eu volto para Ílion batida de ventos,",
        "pois não suporto ver com os meus olhos",
        "o meu filho querido a combater com Menelau, caro a Ares.",
        "Zeus bem sabe, e sabem os outros deuses imortais,",
        "para qual dos dois está marcado o fim da morte.”",
        "Assim falou o homem divino, e pôs os cordeiros no carro;",
        "subiu e puxou as rédeas para trás,",
        "e ao lado dele subiu Antenor, no belo carro;",
        "e os dois voltaram para Ílion.",
        "Então Heitor, filho de Príamo, e o divino Odisseu",
        "mediram primeiro o terreno, e depois tomaram as sortes{1}",
        "e sacudiram-nas num elmo de bronze,",
        "para ver qual dos dois havia de atirar primeiro a lança.",
        "O povo orava e erguia as mãos para os deuses,",
        "e assim dizia um, entre aqueus e troianos:",
        "“Zeus pai, que governas do Ida, gloriosíssimo, grandíssimo:",
        "aquele dos dois que trouxe estas coisas sobre os dois povos,",
        "faze que morra e entre na casa de Hades,",
        "e que para nós haja amizade e juramentos fiéis.”"
      ],
      notas: [
        { termo: "as sortes", texto: "Pedras ou fragmentos marcados, sacudidos num elmo até que um saltasse fora: era assim que se tirava à sorte." }
      ]
    },
    {
      titulo: "Páris se arma",
      versos: "324–339",
      linhas: [
        "Assim diziam; e o grande Heitor do elmo faiscante",
        "sacudiu as sortes, olhando para trás;",
        "e depressa saltou fora a sorte de Páris.",
        "Os outros sentaram-se então em fileiras,",
        "cada um onde estavam os seus cavalos velozes e as suas armas lavradas.",
        "E sobre os ombros o divino Alexandre, marido de Helena de louros cabelos,",
        "pôs as suas belas armas.",
        "Primeiro prendeu às pernas as grevas,",
        "belas, ajustadas com peças de prata nos tornozelos;",
        "depois vestiu no peito a couraça do irmão Licáon,",
        "e ela lhe servia.",
        "Aos ombros lançou a espada de bronze cravejada de prata,",
        "e em seguida o escudo grande e pesado.",
        "Na cabeça forte pôs um elmo bem trabalhado,",
        "com crina de cavalo, e o penacho balançava terrível lá em cima;",
        "e tomou uma lança forte, ajustada à sua mão.",
        "Do mesmo modo o guerreiro Menelau vestiu as armas."
      ]
    },
    {
      titulo: "As lanças",
      versos: "340–360",
      linhas: [
        "Depois de se armarem, cada um do seu lado da multidão,",
        "avançaram para o meio dos troianos e dos aqueus,",
        "olhando terrivelmente; e o espanto tomou os que olhavam —",
        "os troianos domadores de cavalos e os aqueus de belas grevas.",
        "Puseram-se perto um do outro, no espaço medido,",
        "brandindo as lanças, cheios de raiva.",
        "Primeiro Alexandre atirou a lança de longa sombra",
        "e acertou no escudo do filho de Atreu, bem no meio;",
        "mas o bronze não o atravessou: a ponta dobrou-se",
        "contra o escudo forte.",
        "Depois, com o bronze na mão, avançou Menelau, filho de Atreu,",
        "tendo rogado antes a Zeus pai:",
        "“Zeus soberano, dá-me castigar aquele que primeiro me fez o mal,",
        "o divino Alexandre, e dobrá-lo debaixo das minhas mãos,",
        "para que também os homens que nascerem muito depois",
        "tremam de fazer mal a quem os recebeu como hóspedes{1}.”",
        "Assim falou, e, equilibrando a lança de longa sombra, atirou-a",
        "e acertou no escudo do filho de Príamo.",
        "A lança poderosa atravessou o escudo brilhante,",
        "forçou caminho pela couraça bem lavrada",
        "e, rente ao flanco, rasgou-lhe a túnica;",
        "mas ele desviou-se e escapou da morte negra."
      ],
      notas: [
        { termo: "a quem os recebeu como hóspedes", texto: "Páris era hóspede na casa de Menelau quando levou Helena. A hospitalidade estava sob a proteção de Zeus, e trair o anfitrião contava entre as piores ofensas que um grego podia imaginar." }
      ]
    },
    {
      titulo: "A espada partida",
      versos: "361–382",
      linhas: [
        "Então o Atrida puxou a espada de prata cravejada",
        "e, erguendo-a, bateu na crista do elmo;",
        "mas a espada partiu-se em três ou quatro pedaços",
        "e caiu-lhe da mão.",
        "O Atrida gemeu, olhando para o céu largo:",
        "“Zeus pai! Não há deus mais funesto do que tu.",
        "Bem julgava eu castigar Alexandre pela sua maldade;",
        "e agora a espada partiu-se-me nas mãos,",
        "e a lança saiu-me da mão à toa, sem que eu o acertasse.”",
        "Assim falou, e, saltando sobre ele, agarrou-o pela crina do elmo;",
        "e, girando-o, começou a arrastá-lo para os aqueus de belas grevas.",
        "A correia bordada, apertada por baixo do queixo",
        "para segurar o elmo, sufocava-lhe a garganta macia.",
        "E ali o teria arrastado, ganhando glória sem conta,",
        "se Afrodite, filha de Zeus, não visse depressa o que se passava:",
        "partiu-lhe a correia de couro de boi,",
        "e o elmo veio vazio na mão pesada de Menelau.",
        "O herói girou-o e atirou-o entre os aqueus de belas grevas,",
        "e os companheiros fiéis recolheram-no.",
        "Depois saltou outra vez para a frente, querendo matá-lo com a lança;",
        "mas Afrodite arrebatou Páris muito facilmente, como podem os deuses,",
        "escondeu-o numa névoa espessa",
        "e pousou-o no quarto perfumado, de teto abobadado."
      ]
    },
    {
      titulo: "Afrodite chama Helena",
      versos: "383–412",
      linhas: [
        "Ela própria foi chamar Helena. Encontrou-a na torre alta,",
        "com as troianas apinhadas em volta.",
        "Puxou-lhe com a mão o vestido perfumado e sacudiu-o,",
        "e falou-lhe, tomando a figura de uma velha,",
        "uma fiandeira que lhe cardava a lã fina",
        "quando ela vivia na Lacedemônia, e a quem Helena muito estimava.",
        "Com essa aparência, disse a divina Afrodite:",
        "“Vem cá. Alexandre chama-te para ires para casa.",
        "Ele está no quarto, na cama lavrada,",
        "resplandecente de beleza e de roupas.",
        "Ninguém diria que ele acabou de combater com um homem:",
        "parece antes que vai para uma dança, ou que se sentou",
        "tendo acabado de dançar.”",
        "Assim falou, e mexeu com o coração de Helena no peito.",
        "Mas quando esta reparou no belo pescoço da deusa,",
        "no peito desejável e nos olhos brilhantes,",
        "ficou espantada, e disse:",
        "“Ó deusa estranha, por que queres enganar-me assim?",
        "Vais levar-me ainda mais longe, para alguma cidade bem povoada",
        "da Frígia ou da amável Meônia,",
        "se também lá tens algum homem mortal a quem queiras bem —",
        "agora que Menelau venceu o divino Alexandre",
        "e quer levar-me para casa, odiosa como sou?",
        "É por isso que vens aqui, com engano no pensamento?",
        "Vai tu sentar-te ao lado dele; deixa os caminhos dos deuses;",
        "que os teus pés nunca mais te levem de volta ao Olimpo;",
        "vive antes aflita por ele, e guarda-o,",
        "até que ele faça de ti a sua mulher — ou a sua escrava.",
        "Para lá eu não vou: seria vergonhoso",
        "ir arrumar-lhe a cama. As troianas todas",
        "me censurariam depois; e já tenho no coração dores sem medida.”"
      ]
    },
    {
      titulo: "A ameaça da deusa",
      versos: "413–436",
      linhas: [
        "Irada, disse-lhe a divina Afrodite:",
        "“Não me provoques, desgraçada, não vá eu abandonar-te com raiva",
        "e odiar-te tanto quanto agora te amo sem medida,",
        "e armar entre os dois lados, troianos e dânaos,",
        "um ódio pesado — e tu morrerias de má morte.”",
        "Assim falou; e Helena, nascida de Zeus, teve medo.",
        "Foi, envolvendo-se no manto branco e brilhante,",
        "calada, sem que as troianas a vissem; e a deusa ia à frente.",
        "Quando chegaram à bela casa de Alexandre,",
        "as servas voltaram depressa ao seu trabalho,",
        "e ela, divina entre as mulheres, subiu ao quarto de teto alto.",
        "Afrodite, amiga do riso, tomou uma cadeira",
        "e, carregando-a, a deusa pô-la diante de Alexandre.",
        "Ali se sentou Helena, filha de Zeus porta-égide,",
        "desviando os olhos; e censurou o marido:",
        "“Voltaste do combate. Quem dera tivesses morrido lá,",
        "vencido pelo homem forte que foi meu primeiro marido.",
        "Antes te gabavas de seres melhor do que Menelau, caro a Ares,",
        "na força das mãos e com a lança.",
        "Vai então, agora, e desafia Menelau, caro a Ares,",
        "a combater outra vez contigo, frente a frente.",
        "Mas eu te digo que pares, e que não combatas frente a frente",
        "com Menelau de louros cabelos, nem lutes com ele à toa,",
        "para não seres vencido pela lança dele.”"
      ]
    },
    {
      titulo: "Menelau procura na multidão",
      versos: "437–461",
      linhas: [
        "Respondeu-lhe Páris com estas palavras:",
        "“Mulher, não me repreendas o ânimo com censuras tão duras.",
        "Agora, é verdade, Menelau venceu-me, com a ajuda de Atena;",
        "mas outra vez o vencerei eu, pois também nós temos deuses conosco.",
        "Vamos, deitemo-nos e gozemos o amor,",
        "pois nunca o desejo me envolveu assim o espírito —",
        "nem quando te levei da amável Lacedemônia,",
        "navegando nas naves marinhas,",
        "e me deitei contigo na ilha de Cránae{1} —",
        "como agora te amo, e o doce desejo me toma.”",
        "Assim falou, e foi à frente para a cama; e a mulher seguiu-o.",
        "E os dois deitaram-se na cama de correias.",
        "Mas o Atrida percorria a multidão como uma fera,",
        "a ver se descobria o divino Alexandre.",
        "Nenhum dos troianos, porém, nem dos aliados ilustres,",
        "soube mostrar Alexandre a Menelau, caro a Ares;",
        "e não o teriam escondido por amizade, se algum o tivesse visto,",
        "pois era odiado por todos eles como a morte negra.",
        "Então falou-lhes Agamêmnon, soberano de homens:",
        "“Ouvi-me, troianos, dárdanos e aliados.",
        "A vitória está claramente com Menelau, caro a Ares.",
        "Entregai Helena de Argos e os bens que vieram com ela,",
        "e pagai a reparação que for justa,",
        "de modo que fique lembrada entre os homens que vierem depois.”",
        "Assim falou o Atrida; e os outros aqueus aclamaram."
      ],
      notas: [
        { termo: "a ilha de Cránae", texto: "Ilha onde Páris e Helena passaram a primeira noite depois da fuga de Esparta." }
      ]
    }
  ]
});
